### PR TITLE
rocks: fix make command

### LINKED ISSUE #114: Fix tt rocks make
### What happened
I have faced with some problem of `tt rocks make` work.

### My environment:
```
Ubuntu Release:	20.04
Linux version 5.4.0-42-generic (buildd@lgw01-amd64-038) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2))
Golang version: go1.18.5 linux/amd64
tt: master branch
Tarantool: 2.11.0-entrypoint-358-g9965e3fe4
```

### My actions:
1. Building go, mage and then tt from sources and install it to the system.
2. Writing simple `.rockspec` file. My `myapp-scm-1.rockspec`:
```
package = 'myapp'
version = 'scm-1'
source  = {
    url = '/dev/null',
}
-- Put any modules your app depends on here
dependencies = {
    'tarantool',
    'lua >= 5.1',
    'checks == 3.1.0-1',
    'cartridge == 2.7.4-1',
    'metrics == 0.13.0-1',
    'cartridge-cli-extensions == 1.1.1-1',
}
build = {
    type = 'none';
}
```
3. Calling `tt rocks make` in the directory, where `.rockspec` file is located.
4. Getting the next output:
```shell
$ tt rocks make
Warning: Could not find a Lua 5.1 interpreter in your PATH. Modules may not install with the correct configurations. You may want to specify to the path prefix to your build of Lua 5.1 using --lua-dir
Missing dependencies for myapp scm-1:
   tarantool (not installed)
   cartridge 2.7.4-1 (not installed)
   metrics 0.13.0-1 (not installed)
   cartridge-cli-extensions 1.1.1-1 (not installed)

myapp scm-1 depends on tarantool (not installed)
tarantool not found for Lua 5.1.
Checking if available for other Lua versions...
Checking for Lua 5.2...
Checking for Lua 5.3...
Checking for Lua 5.4...

Error: Could not satisfy dependency tarantool: No results matching query were found for Lua 5.1.
```

Meanwhile `tarantoolctl` has no problems with building it:

```shell
$ tarantoolctl rocks make
Missing dependencies for myapp scm-1:
   cartridge 2.7.4-1 (not installed)
   metrics 0.13.0-1 (not installed)
   cartridge-cli-extensions 1.1.1-1 (not installed)

myapp scm-1 depends on cartridge 2.7.4-1 (not installed)
Installing http://rocks.tarantool.org/cartridge-2.7.4-1.all.rock
Missing dependencies for cartridge 2.7.4-1:
   vshard 0.1.19-1 (not installed)
   membership 2.4.0-1 (not installed)
   frontend-core 8.1.1-1 (not installed)
   graphql 0.1.4-1 (not installed)

cartridge 2.7.4-1 depends on vshard 0.1.19-1 (not installed)
Installing http://rocks.tarantool.org/vshard-0.1.19-1.src.rock

-- The C compiler identification is GNU 9.4.0
...
...
...
```

It doesn't seem to be related with OS, I have reproduced the same problem on MacOS.

### PR DESCRIPTION
**Pull request by 0x501D**
When the spec file contains a tarantool dependency, luarocks
checks the tarantool version against the _TARANTOOL global variable.
Since luarocks ran inside the tarantool in tarantoolctl, there were
no problems with this. Luarocks launched from tt
is served by gopher-lua and has no direct access to tarantool variables,
accordingly, a new way of checking dependencies was added, namely:

Added variables TT_CLI_TARANTOOL_PATH and TT_CLI_TARANTOOL_VERSION.

This will allow luarocks to correctly add tarantool to the list of
dependencies and run the correct version of tarantool for internal needs.

Also in this patch are outlines for solving the problem with the correct
determination of the path to the directory with the header files of the
tarantool.

`tt rocks make` test was added.

Also, to solve this problem, a commit was made in luarocks:
https://github.com/tarantool/luarocks/pull/12

Closes #114

### CODE REVIEW

File: cli/util/util.go [hunk 1]
```diff
@@ -243,6 +246,28 @@ func GetLastNLines(filepath string, linesN int) ([]string, error) {
 	return lines, nil
 }
 
+func GetTarantoolVersion(cli *cmdcontext.CliCtx) (string, error) {
```
Comment (LeonidVas) [inline cli/util/util.go:249]: It's a public function. Add description.

Comment (0x501D) [reply cli/util/util.go:250]: Added.

**Review by better0fdead — APPROVED** [review]
