### PR TITLE
completion: added luarocks completions

### LINKED ISSUE #616: tt rocks: fix completion commands
Luarocks version 3.9.2 added built-in commands: `completion` and `admin completion`

Not this commands fails:
```sh
./tt rocks completion bash
   ⨯ <string>:1316: assertion failed!
stack traceback:
	[G]: in function 'assert'
	<string>:1316: in function <<string>:1314>
	<string>:1196: in function 'action'
	<string>:1793: in function 'close'
	<string>:1747: in function 'pass'
	<string>:1919: in function 'pass'
	<string>:2045: in function <<string>:1990>
	(tailcall): ?
	(tailcall): ?
	<string>:573: in function 'run_command'
	<string>:29: in function 'exec'
	<string>:1: in main chunk
	[G]: ?
```
It is necessary to fix these commands or disable them (it won’t work normally using the wrapper.lua wrapper)

### PR DESCRIPTION
**Pull request by 0x501D**
added luarocks completions. The `tt rocks completion` and `tt rock admin completion` commands are disabled.

Closes #616 #44

### CODE REVIEW

File: cli/cmd/completion.go [hunk 1]
```diff
@@ -46,17 +48,54 @@ func RootShellCompletionCommands(cmd *cobra.Command, args []string,
...
+	idx := bytes.Index(completion, label)
+	if idx == -1 {
+		return nil, fmt.Errorf("failed to inject LuaRocks completions")
+	}
+	res.Write(completion[:idx])
+	res.Write([]byte(injection))
+	res.Write(completion[idx:])
+	res.Write([]byte(rocks))
+
+	return res.Bytes(), nil
```
Comment (psergee) [inline cli/cmd/completion.go:74]: Let's add a test to check that at least `source` command works fine after this injection.

**Review by psergee — APPROVED** [review]
Thanks for the patch.

File: cli/cmd/completion.go (hunk 1 above)
Comment (0x501D) [reply cli/cmd/completion.go:74]: Test added.
