### PR TITLE
install: fix static build

### LINKED ISSUE #175: install: fix static build
We must patch tarantool repo before build from sources:

* backport static-build
* apply patches from gentoo tarantool repo: gh-6686-fix-build-with-glibc-2-34.patch
* maybe need more patches...

### PR DESCRIPTION
**Pull request by 0x501D**
Backported static build system for versions 1.10.
    
For the successful assembly of older versions,
additional patches have been applied:
    
    * openssl-symbols.patch - Fix missing OpenSSL symbols.
    * gh-6686-fix-build-with-glibc-2-34.patch - Necessary
      for building with >= glibc-2.34.
    * zlib-backup.patch - zlib version 1.2.11 is no longer
      available for download.
    * bump-libunwind.patch - Old version of the libunwind
      doesn't compile under GCC > 10.
    
Closes #175

### CODE REVIEW

File: cli/install/patch.go [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+
+type defaultPatchApplier struct {
+	patch []byte
+}
+
+func (applier defaultPatchApplier) apply(srcPath string, verbose bool, logFile *os.File) error {
+	err := util.ExecuteCommandStdin("git", verbose, logFile,
+		srcPath, applier.patch, "apply")
+
+	if err != nil {
```
Comment (psergee) [inline cli/install/patch.go:23]: Can we just use `return err` here?

File: cli/search/search.go [hunk 2]
```diff
@@ -20,15 +20,20 @@ const (
 	GitRepoTT        = "https://github.com/tarantool/tt.git"
 )
 
-// isDeprecated checks if the program version is lower than 1.10.0.
-func isDeprecated(version string) bool {
-	splitedVersion := strings.Split(version, ".")
-	if len(splitedVersion) < 2 {
-		return false
+// isDeprecated checks if the program version is lower than 1.10.11
```
Comment (psergee) [inline cli/search/search.go:23]: As I can see 2.7 is also checked.

**Review by psergee — APPROVED** [review]

File: cli/install/patch.go (hunk 1 above)
Comment (0x501D) [reply cli/install/patch.go]: FIxed

File: cli/search/search.go (hunk 2 above)
Comment (0x501D) [reply cli/search/search.go]: Changed

**Review by psergee — APPROVED** [review]

**Review by LeonidVas — APPROVED** [review]
Hi! Thank you for the patchset. Great work!
"install: removed duplicated code" -> "install: remove duplicated code"
Rebase on master.

**Comment by 0x501D** [comment]
> Hi! Thank you for the patchset. Great work! "install: removed duplicated code" -> "install: remove duplicated code" Rebase on master.

Fixed
