### PR TITLE
tls: build without openssl linkage

### LINKED ISSUE #1101: build: return ability to build without OpenSSL linking
We already had the ability to build `tt` without linking with `OpenSSL` and with CGO_ENABLED=0:
https://github.com/tarantool/tt/blob/648f98a29f597175a59f7f1166541d030eb7b87d/magefile.go#L67

But it was broken with the `go-tarantool/v2` by directly usage of the `go-tlsdialer`. We could return the ability to build without OpenSSL with a build tag inside `tt` (and optional usage of the `go-tlsdialer`). See `go-tarantool/v1` as an example:

https://github.com/tarantool/go-tarantool/blob/v1.12.2/ssl.go#L1-L2
https://github.com/tarantool/go-tarantool/blob/6843830d225bd5dc7c5ec50acc6f02bb73ab5c56/ssl_disable.go#L1-L2

### PR DESCRIPTION
**Pull request by patapenka-alexey**
Closes #1101

### CODE REVIEW

File: lib/dial/opts.go [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+const (
+	TransportDefault Transport = ""
+	TransportPlain   Transport = "plain"
+	TransportSSL     Transport = "ssl"
+	TransportInvalid Transport = "invalid"
+)
+
+func ConvertTransport(tr string) Transport {
+	switch tr {
+	case "":
```
Comment (oleg-jukovec) [inline lib/dial/opts.go:19]: Or we could do something like that to avoid duplication:
```suggestion
	case TransportDefault.String():
```

File: lib/dial/opts.go [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+	User            string
+	Password        string
+	SslKeyFile      string
+	SslCertFile     string
+	SslCaFile       string
+	SslCiphers      string
+	SslPassword     string
+	SslPasswordFile string
+	Transport       string
+}
```
Comment (oleg-jukovec) [inline lib/dial/opts.go:41]: Please, move it into opts.go file.

File: lib/dial/opts.go [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+	case "":
+		return TransportDefault
+	case "plain":
+		return TransportPlain
+	case "ssl":
+		return TransportSSL
+	default:
+		return TransportInvalid
+	}
+}
```
Comment (oleg-jukovec) [inline lib/dial/opts.go:28]: Please, move it into transport.go.

File: cli/cluster/cluster.go [hunk 4]
```diff
@@ -96,35 +96,29 @@ func collectTarantoolConfig(collectors libcluster.CollectorFactory,
...
+			Address:         addr,
+			User:            endpoint.Login,
+			Password:        endpoint.Password,
+			SslKeyFile:      endpoint.Params.SslKeyFile,
+			SslCertFile:     endpoint.Params.SslCertFile,
+			SslCaFile:       endpoint.Params.SslCaFile,
+			SslCiphers:      endpoint.Params.SslCiphers,
+			SslPassword:     endpoint.Params.SslPassword,
+			SslPasswordFile: endpoint.Params.SslPasswordFile,
+			Transport:       endpoint.Params.Transport, // [ssl|plain]
```
[the remark this answers is not in the document]
Comment (patapenka-alexey) [reply cli/cluster/cluster.go:110]: Cause this is `draft` PR.

File: cli/cluster/cluster.go [hunk 5]
```diff
@@ -96,35 +96,29 @@ func collectTarantoolConfig(collectors libcluster.CollectorFactory,
...
+		})
+		if err != nil {
+			return nil, err
 		}
+		opts = append(opts, tarantoolOpts{
+			addr:   addr,
+			dialer: dialer,
+			opts: tarantool.Opts{
```
[the remark this answers is not in the document]
Comment (patapenka-alexey) [reply cli/cluster/cluster.go:119]: `go fmt` removes this space.

File: lib/dial/transport.go [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+
+import "fmt"
+
+const (
+	transportDefault string = ""
+	transportPlain   string = "plain"
+	transportSsl     string = "ssl"
+)
+
+//go:generate stringer -type Transport -trimprefix Transport -linecomment
```
Comment (oleg-jukovec) [inline lib/dial/transport.go:11]: Please, add a test for the String() function to make sure that everything work fine:

https://github.com/tarantool/go-discovery/blob/master/eventtype_test.go

You could also add tarantport_string.go to the commit. The stringer-generated code usually included into a commit.

File: lib/dial/dial.go [hunk 7]
```diff
@@ -0,0 +1,37 @@
+package dial
+
+import (
+	"fmt"
+
+	"github.com/tarantool/go-tarantool/v2"
+)
+
+// Dial creates new dialer according to the options.
+func New(opts Opts) (tarantool.Dialer, error) {
```
Comment (oleg-jukovec) [inline lib/dial/dial.go:10]: We could add unit-tests here. Something like:

```Go
func TestNew(t *testing.T) {
    cases := []struct{
        name     string
        opts        dial.Opts
        expected tarantool.DIaler
    } {
        {
            Name: "simple",
            Opts: dial.Opts{foo},
            expected: tarantool.NetDialer{foo},
        }
        ...
    }
    
    for _, tc := range cases {
        dialer, err := dial.New(tc.opts)

        require.NoError(t, err)
        require.Equal(t, tc.expected, dialer)
    } 
}
```

For simplicity we can test this only with ssl enabled. But you can make two different test files. See
https://github.com/tarantool/go-tarantool/blob/461ad486865e0f401a46568a688ec0851b2aa020/ssl_test.go#L1-L2

File: lib/dial/transporttype_test.go
Comment (oleg-jukovec) [inline lib/dial/transporttype_test.go:1]: Please, rename it -> `transport_test.go`

File: lib/dial/transport.go [hunk 8]
```diff
@@ -0,0 +1,50 @@
...
+func (t Transport) String() string {
+	switch t {
+	case TransportDefault:
+		return transportDefault
+	case TransportPlain:
+		return transportPlain
+	case TransportSsl:
+		return transportSsl
+	default:
+		panic("Unknown Transport")
```
Comment (oleg-jukovec) [inline lib/dial/transport.go:48]: Please, avoid panics. Return something like a usual String() generated by a stringer return:
```suggestion
		return fmt.Sprintf("Transport(%d)", t)
```

File: lib/dial/transporttype_test.go [hunk 9]
```diff
@@ -0,0 +1,24 @@
...
+
+func TestTransportType_String(t *testing.T) {
+	cases := []struct {
+		Transport Transport
+		Expected  string
+	}{
+		{TransportDefault, ""},
+		{TransportPlain, "plain"},
+		{TransportSsl, "ssl"},
+	}
```
Comment (oleg-jukovec) [inline lib/dial/transporttype_test.go:17]: Don't forget to add a case with unsupported value here.

**Review by oleg-jukovec — APPROVED** [review]
LGTM, but required a few non-critical improvments.

File: lib/dial/transporttype_test.go (hunk 9 above)
Comment (oleg-jukovec) [reply lib/dial/transporttype_test.go:17]: ```Transport(15).String()```

**Review by AlexandrLitkevich — APPROVED** [review]
