### PR TITLE
connect: fix Lua parse error handling - return instead of ignoring

### LINKED ISSUE #1064: `tt connect` console ignores syntax errors
**Bug description**

In contrast to the built-in Tarantool `console` module, `tt connect` console doesn't raise any error if the input string contains syntax errors. Instead it returns `null`.

**Version**

Tarantool CLI version 2.6.0, linux/amd64. commit: 96db0688623b (v2.6.0-10-g96db0688623b)

**Steps to reproduce**

1. Create a test instance.
   ```sh
   tt init
   tt create single_instance --name test
   tt start
   ```

2. Connect to the console.
   ```sh
   tt connect test:instance001
   ```
3. Type an invalid Lua string.
   ```
   hello)
   ```

**Actual behavior**

```
test:instance001> hello)
---
- null
...
```

**Expected behavior**

```
test:instance001> hello)
---
- error: '[string "hello)"]:1: ''='' expected near '')'''
...
```

### PR DESCRIPTION
**Pull request by d-enk**
close #1064

solution emulation on version 2.7.0 by evaler

```
echo "hello)" | tt connect --evaler '_, errmsg = loadstring(cmd); box.error(box.error.PROC_LUA,  errmsg)' $TARANTOOL_CONSOLE_URI
---
- error: '[string "hello)"]:1: ''='' expected near '')'''
...
```

### CODE REVIEW

File: cli/connect/internal/luabody/eval_func_body.lua [hunk 1]
```diff
@@ -23,7 +23,7 @@ if not fun then
     fun, errmsg = loadstring(cmd)
 end
 if not fun then
-    return yaml.encode({box.NULL})
+    return box.error(box.error.PROC_LUA, errmsg)
```
Comment (patapenka-alexey) [inline cli/connect/internal/luabody/eval_func_body.lua:26]: Your solution causes the connection closing in case of invalid command. I think it would be better just to print the error:
```suggestion
    return yaml.encode({ errmsg })
```

Comment (d-enk) [reply cli/connect/internal/luabody/eval_func_body.lua:26]: For some reason I didn't try to just `return {error = errmsg}`

it save same behavior
```
echo "hello)" | tt connect --evaler '_, errmsg = loadstring(cmd); return { error = errmsg }' $TARANTOOL_CONSOLE_URI
---
- error: '[string "hello)"]:1: ''='' expected near '')'''
...
```

unlike `return yaml.encode({ error = errmsg })`
```
echo "hello)" | tt connect --evaler '_, errmsg = loadstring(cmd); return yaml.encode({ error = errmsg })' $TARANTOOL_CONSOLE_URI
---
- |
  ---
  error: '[string "hello)"]:1: ''='' expected near '')'''
  ...
...
```

**Comment by patapenka-alexey** [comment]
Please, add an entry to the [CHANGELOG.md](https://github.com/tarantool/tt/blob/master/CHANGELOG.md) `Fixed` section.

**Review by patapenka-alexey — COMMENTED** [review]
First of all - thank you for the patch!
But it would be perfect to add the [test](https://github.com/tarantool/tt/blob/master/test/integration/connect/test_connect.py) too.

**Comment by d-enk** [comment]
> But it would be perfect to add the [test](https://github.com/tarantool/tt/blob/master/test/integration/connect/test_connect.py) too.


> Please, add an entry to the [CHANGELOG.md](https://github.com/tarantool/tt/blob/master/CHANGELOG.md) `Fixed` section.

Done

File: test/integration/connect/test_connect.py [hunk 2]
```diff
@@ -297,6 +297,57 @@ def test_connect_and_get_commands_errors(tt_cmd, tmpdir_with_cfg):
...
+
+    formats["ttable"] = (
+        '''+-------+--------------------------------------------+\n'''
+        f'''| error | [string "{cmd}"]:1: '=' expected near ')' |\n'''
+        '''+-------+--------------------------------------------+\n'''
+    )
+
+    try:
+        for format, expected in formats.items():
+            ret, output = try_execute_on_instance(tt_cmd, tmpdir, "localhost:3013", stdin=cmd,  opts={"-x": format})
```
Comment (patapenka-alexey) [inline test/integration/connect/test_connect.py:344]: If you run [python linter](https://github.com/tarantool/tt/blob/da304aae43ed37ab80dd1c397dada1eddbc21797/.github/actions/static-code-check/action.yml#L33) , you will see than this line is too long.

```suggestion
            ret, output = try_execute_on_instance(tt_cmd, tmpdir, "localhost:3013",
                                                  stdin=cmd,  opts={"-x": format})
```

File: test/integration/connect/test_connect.py [hunk 3]
```diff
@@ -297,6 +297,57 @@ def test_connect_and_get_commands_errors(tt_cmd, tmpdir_with_cfg):
...
+            assert ret
+
+            assert expected == output
```
Comment (patapenka-alexey) [inline test/integration/connect/test_connect.py:347]: Let's make the code a little bit cleaner.
```suggestion
            assert expected in output
```

File: test/integration/connect/test_connect.py [hunk 4]
```diff
@@ -297,6 +297,57 @@ def test_connect_and_get_commands_errors(tt_cmd, tmpdir_with_cfg):
...
+"""
+
+    formats["lua"] = f'''{{error = "[string "{cmd}"]:1: '=' expected near ')'"}};\n'''
+
+    formats["table"] = (
+        '''+--------------------------------------------+\n'''
+        '''| error                                      |\n'''
+        '''+--------------------------------------------+\n'''
+        f'''| [string "{cmd}"]:1: '=' expected near ')' |\n'''
+        '''+--------------------------------------------+\n'''
```
Comment (patapenka-alexey) [inline test/integration/connect/test_connect.py:333]:
```suggestion
        f'''| [string "{cmd}"]:1: '=' expected near ')' |\n'''
```

File: test/integration/connect/test_connect.py [hunk 5]
```diff
@@ -297,6 +297,57 @@ def test_connect_and_get_commands_errors(tt_cmd, tmpdir_with_cfg):
...
+    )
+
+    formats["ttable"] = (
+        '''+-------+--------------------------------------------+\n'''
+        f'''| error | [string "{cmd}"]:1: '=' expected near ')' |\n'''
+        '''+-------+--------------------------------------------+\n'''
```
Comment (patapenka-alexey) [inline test/integration/connect/test_connect.py:339]:
```suggestion
        f'''| error | [string "{cmd}"]:1: '=' expected near ')' |\n'''
```

**Review by patapenka-alexey — CHANGES_REQUESTED** [review]
Please, make required cosmetic changes, and I will approve.

File: test/integration/connect/test_connect.py (hunk 2 above)
Comment (d-enk) [reply test/integration/connect/test_connect.py]: My bad.
I'm not a python programmer and accidentally disabled python linter with heavy golangci)

**Comment by d-enk** [comment]
> Please, make required cosmetic changes, and I will approve.

Done.

**Comment by patapenka-alexey** [comment]
Thank you for the fixes. But there is another one place I missed before. Could you please rewrite commit message according to the [rules](https://www.tarantool.io/en/doc/latest/contributing/developer_guidelines/#how-to-write-a-commit-message)?

**Review by patapenka-alexey — APPROVED** [review]

**Review by dmyger — APPROVED** [review]
