### PR TITLE
pack: skip unavailable configs from etcd and tcs

### LINKED ISSUE #1038: tt pack завершается ошибкой при недоступном etcd
### Описание
Команда `tt pack tgz` завершается ошибкой в случае недоступности etcd:
```bash
   ⨯ error collect applications info: failed to collect applications info: can't collect instance information for test_app: error loading instance "storage-002-a" configuration from config "/app/test/instances.enabled/test_app/config.yaml": unable to connect to etcd: context deadline exceeded
```

Команда `tt pack` должна разрешать выполнение в случае недоступности etcd в данный момент.

### Репродьюссер
```bash
$ tt version
Tarantool CLI EE 2.4.0, linux/amd64. commit: d5f731b

$ tt create vshard_cluster --name test_app

$ cat >> test_app/config.yaml <<EOL
config:
  etcd:
    endpoints:
    - http://localhost:2379
    prefix: /test_app
    username: client
    password: secret
    http:
      request:
        timeout: 3
EOL

$ tt pack tgz --name test_app
⨯ error collect applications info: failed to collect applications info: can't collect instance information for test2_app: error loading instance "router-001-a" configuration from config "/app/test/instances.enabled/test_app/config.yaml": unable to connect to etcd: context deadline exceeded
```

### PR DESCRIPTION
**Pull request by patapenka-alexey**
Closes #1038

@TarantoolBot document
Title: pack: skip unavailable configs from etcd and tcs

This patch fixes the `tt pack` error if `etcd` or `tcs` are unavailable during package creation.

### CODE REVIEW

File: test/integration/pack/test_bundles/vshard_app/test_app/router.lua [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+-- Bootstrap the vshard router.
+while true do
+    local ok, err = vshard.router.bootstrap({
+        if_not_bootstrapped = true,
+    })
+    if ok then
+        break
+    end
+    log.info(('Router bootstrap error: %s'):format(err))
+end
```
Comment (tecl1s) [inline test/integration/pack/test_bundles/vshard_app/test_app/router.lua:13]: Такой вызов bootstrap иногда может приводить к ошибкам в кластере из-за многократного вызова vshard.router.bootstrap:
```bash
test_app:router> vshard.router.info()
---
- replicasets:
   ...
  alerts:
  - ['UNKNOWN_BUCKETS', '15000 buckets are not discovered']
```
Так же это противоречит [документации vshard](https://www.tarantool.io/en/doc/latest/reference/reference_rock/vshard/vshard_router/#lua-function.vshard.router.bootstrap)

File: cli/running/running.go [hunk 2]
```diff
@@ -348,7 +348,7 @@ func loadInstanceConfig(configPath, instName string,
 
 // collectInstancesFromAppDir collects instances information from application directory.
 func collectInstancesFromAppDir(appDir string, selectedInstName string,
-	integrityCtx integrity.IntegrityCtx, instancesScriptsRequired bool) (
+	integrityCtx integrity.IntegrityCtx, configRequired bool) (
```
Comment (oleg-jukovec) [inline cli/running/running.go:351]: The behavior is too complex, not obvious and fault-tolerate now. Probably we need to skip a config load at all if a data from config is not required.

```suggestion
	integrityCtx integrity.IntegrityCtx, skipClusterConfig bool) (
```

Please, try to skip a config load in a **separate** commit.

**Review by oleg-jukovec — COMMENTED** [review]
Please, add an entry into CHANGELOG.md.

File: cli/pack/opts.go [hunk 3]
```diff
@@ -49,7 +49,7 @@ func initAppsInfo(cliOpts *config.CliOpts, cmdCtx *cmdcontext.CmdCtx, packCtx *P
 	}
 	packCtx.AppList = appList
 	packCtx.AppsInfo, err = running.CollectInstancesForApps(packCtx.AppList, cliOpts,
-		cmdCtx.Cli.ConfigDir, cmdCtx.Integrity, true)
+		cmdCtx.Cli.ConfigDir, cmdCtx.Integrity, false)
```
Comment (elhimov) [inline cli/pack/opts.go:52]: It looks like the same approach is to be applied to both instances scripts and cluster config. So both of them are required or both of them are optional and it seems wrong in case of `tt pack`. I'm not sure about cluster config, maybe it's correct that we treat it as configuration and thus able to drop from package, but it seems we are not able to treat instances scripts in the same because they contains business logic and thus look like the essential part of the package.

Comment (elhimov) [reply cli/pack/opts.go:52]: And regardless of our ability to drop some part of package while preparing it, it looks quite weird that content of the package depends on current availability of some items. What if next time one pack the same application but etcd/tcs config is available? As the content is changed we will get another package for the same application. Do we expect such a behavior?

File: test/integration/pack/test_bundles/vshard_app/test_app/router.lua (hunk 1 above)
Comment (patapenka-alexey) [reply test/integration/pack/test_bundles/vshard_app/test_app/router.lua:13]: [will be fixed as part of the work on this task](https://github.com/tarantool/tt/issues/1071)

File: test/integration/pack/test_pack.py [hunk 4]
```diff
@@ -520,6 +526,36 @@ def prepare_tgz_test_cases(tt_cmd) -> list:
...
+            "res_file": "test_app-0.1.0.0." + get_arch() + ".tar.gz",
+            "check_exist": [
+                os.path.join("bin", "tarantool"),
+                os.path.join("bin", "tt"),
+                os.path.join("instances.enabled", "test_app"),
+                os.path.join("tt.yaml"),
+                os.path.join("test_app/config.yaml"),
+                os.path.join("test_app/instances.yaml"),
+                os.path.join("test_app/router.lua"),
+                os.path.join("test_app/storage.lua"),
```
Comment (dmyger) [inline test/integration/pack/test_pack.py:544]: What exactly joined here?
```suggestion
                "tt.yaml",
                "test_app/config.yaml",
                "test_app/instances.yaml",
                "test_app/router.lua",
                "test_app/storage.lua",
```

File: test/integration/pack/test_pack.py [hunk 5]
```diff
@@ -520,6 +526,36 @@ def prepare_tgz_test_cases(tt_cmd) -> list:
...
+            ],
+            "check_not_exist": [
+                os.path.join("test_app/test_app-scm-1.rockspec"),
+                os.path.join("test_app/tt.yaml"),
```
Comment (dmyger) [inline test/integration/pack/test_pack.py:548]: Why we should use `join` here?
```suggestion
                "test_app/test_app-scm-1.rockspec",
                "test_app/tt.yaml",
```

File: test/integration/pack/test_pack.py (hunk 4 above)
Comment (patapenka-alexey) [reply test/integration/pack/test_pack.py]: Removed.

File: test/integration/pack/test_pack.py (hunk 5 above)
Comment (patapenka-alexey) [reply test/integration/pack/test_pack.py]: Removed.

**Review by dmyger — APPROVED** [review]

File: CHANGELOG.md [hunk 6]
```diff
@@ -33,6 +33,8 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
 
 - `tt coredump inspect`: fails for tarantool-ee coredump archive if the source
   directory is missing.
+- `tt pack`: fails if `etcd` or `tcs` are present in the configuration
+and not available.
```
Comment (oleg-jukovec) [inline CHANGELOG.md:37]:
```suggestion
- `tt pack`: fails if `etcd` or `tcs` are present in the configuration
  and not available.
```

File: cli/cmd/replicaset.go [hunk 7]
```diff
@@ -497,7 +497,7 @@ func replicasetFillCtx(cmdCtx *cmdcontext.CmdCtx, ctx *replicasetCtx, args []str
 	}
 	var connOpts connector.ConnectOpts
 
-	if err := running.FillCtx(cliOpts, cmdCtx, &ctx.RunningCtx, args, false); err == nil {
+	if err := running.FillCtx(cliOpts, cmdCtx, &ctx.RunningCtx, args, true); err == nil {
```
Comment (oleg-jukovec) [inline cli/cmd/replicaset.go:500]:
```suggestion
	if err := running.FillCtx(cliOpts, cmdCtx, &ctx.RunningCtx, args, false); err == nil {
```

File: cli/cmd/replicaset.go [hunk 8]
```diff
@@ -518,7 +518,7 @@ func replicasetFillCtx(cmdCtx *cmdcontext.CmdCtx, ctx *replicasetCtx, args []str
 				}
 				// Re-fill context for an application.
 				ctx.InstName = instName
-				err := running.FillCtx(cliOpts, cmdCtx, &ctx.RunningCtx, []string{appName}, false)
+				err := running.FillCtx(cliOpts, cmdCtx, &ctx.RunningCtx, []string{appName}, true)
```
Comment (oleg-jukovec) [inline cli/cmd/replicaset.go:521]:
```suggestion
				err := running.FillCtx(cliOpts, cmdCtx, &ctx.RunningCtx, []string{appName}, false)
```

File: cli/running/running.go [hunk 9]
```diff
@@ -376,7 +376,8 @@ func collectInstancesFromAppDir(appDir string, selectedInstName string,
 					InstName:       filepath.Base(appDir),
 					AppDir:         appDir,
 					SingleApp:      true}}, nil
-			} else if instancesScriptsRequired {
+			}
+			if !skipClusterConfig {
```
Comment (oleg-jukovec) [inline cli/running/running.go:380]: The logic is incorrect here: you are not skip a cluster config load, but skip an error if unable to load a config.

**Review by oleg-jukovec — CHANGES_REQUESTED** [review]

**Review by oleg-jukovec — CHANGES_REQUESTED** [review]
We still not skip a config load, but load a config and skip an error.

**Comment by patapenka-alexey** [comment]
I will update the second commit message after we discussed final solution.

File: cli/running/running.go [hunk 10]
```diff
@@ -126,6 +126,14 @@ type providerImpl struct {
 	instanceCtx *InstanceCtx
 }
 
+type SkipClusterConfig int
```
Comment (elhimov) [inline cli/running/running.go:129]: This type name confuses me. It will affect not only cluster config but also instances scripts. I would use  for type name something more general, like `LoadMode` or  similar and specific name for certain enum values (see below).

File: cli/running/running.go [hunk 11]
```diff
@@ -126,6 +126,14 @@ type providerImpl struct {
...
+
+const (
+	SkipConfig       SkipClusterConfig = iota // Skip cluster config loading at all.
+	SkipConfigErrors                          // Skip errors at cluster config loading.
+	LoadConfig                                // Load cluster config, trigger an errors if not.
```
Comment (elhimov) [inline cli/running/running.go:134]:
```suggestion
	SkipScriptsAndClusterConfig       LoadMode = iota // Skip loading of instances scripts and cluster config.
	IgnoreClusterConfigErrors                          // Skip errors at cluster config loading.
	LoadScriptsAndClusterConfig                                // Load instances scripts and cluster config, trigger an errors if not.
```

**Comment by elhimov** [comment]
Please, mark the PR as ready for review (it is draft now).

File: cli/running/running.go (hunk 11 above)
Comment (oleg-jukovec) [inline cli/running/running.go:134]: The idiomatic way to name a enums in Go:
```suggestion
	ConfigSkip       SkipClusterConfig = iota // Skip cluster config loading at all.
	ConfigLoadWIthErrors                          // Skip errors at cluster config loading.
	ConfigLoad                                // Load cluster config, trigger an errors if not.
```

Comment (oleg-jukovec) [reply cli/running/running.go:134]:
```
LoadMode
```

```
LoadConfigSkip
LoadConfigSkipErrors
LoadConfigAlways
```

File: cli/cmd/clean.go [hunk 12]
```diff
@@ -104,7 +104,7 @@ func internalCleanModule(cmdCtx *cmdcontext.CmdCtx, args []string) error {
 	}
 
 	var runningCtx running.RunningCtx
-	if err := running.FillCtx(cliOpts, cmdCtx, &runningCtx, args, false); err != nil {
+	if err := running.FillCtx(cliOpts, cmdCtx, &runningCtx, args, running.SkipConfig); err != nil {
```
Comment (oleg-jukovec) [inline cli/cmd/clean.go:107]: load

File: cli/cmd/connect.go [hunk 13]
```diff
@@ -140,7 +140,8 @@ func resolveConnectOpts(cmdCtx *cmdcontext.CmdCtx, cliOpts *config.CliOpts,
 	newArgs = args[1:]
 	// FillCtx returns error if no instances found.
 	var runningCtx running.RunningCtx
-	if fillErr := running.FillCtx(cliOpts, cmdCtx, &runningCtx, args, false); fillErr == nil {
+	if fillErr := running.FillCtx(
+		cliOpts, cmdCtx, &runningCtx, args, running.SkipConfigErrors); fillErr == nil {
```
Comment (oleg-jukovec) [inline cli/cmd/connect.go:144]: Load?

File: cli/cmd/logrotate.go [hunk 14]
```diff
@@ -42,7 +42,7 @@ func internalLogrotateModule(cmdCtx *cmdcontext.CmdCtx, args []string) error {
 	}
 
 	var runningCtx running.RunningCtx
-	if err := running.FillCtx(cliOpts, cmdCtx, &runningCtx, args, false); err != nil {
+	if err := running.FillCtx(cliOpts, cmdCtx, &runningCtx, args, running.SkipConfig); err != nil {
```
Comment (oleg-jukovec) [inline cli/cmd/logrotate.go:45]: Load?

File: cli/cmd/play.go [hunk 15]
```diff
@@ -99,7 +99,8 @@ func internalPlayModule(cmdCtx *cmdcontext.CmdCtx, args []string) error {
 	// FillCtx returns error if no instances found.
 	var runningCtx running.RunningCtx
 
-	if err := running.FillCtx(cliOpts, cmdCtx, &runningCtx, []string{args[0]}, false); err == nil {
+	if err := running.FillCtx(
+		cliOpts, cmdCtx, &runningCtx, []string{args[0]}, running.SkipConfig); err == nil {
```
Comment (oleg-jukovec) [inline cli/cmd/play.go:103]: Load.

File: cli/cmd/replicaset.go [hunk 16]
```diff
@@ -518,7 +519,8 @@ func replicasetFillCtx(cmdCtx *cmdcontext.CmdCtx, ctx *replicasetCtx, args []str
 				}
 				// Re-fill context for an application.
 				ctx.InstName = instName
-				err := running.FillCtx(cliOpts, cmdCtx, &ctx.RunningCtx, []string{appName}, false)
+				err := running.FillCtx(
```
Comment (oleg-jukovec) [inline cli/cmd/replicaset.go:522]: Load, expected `replicaset status`.

File: cli/instances/list.go [hunk 17]
```diff
@@ -31,7 +31,7 @@ func ListInstances(cmdCtx *cmdcontext.CmdCtx, cliOpts *config.CliOpts) error {
 	fmt.Printf("instances enabled directory: %s\n", cliOpts.Env.InstancesEnabled)
 
 	applications, err := running.CollectInstancesForApps(appList, cliOpts, cmdCtx.Cli.ConfigDir,
-		cmdCtx.Integrity, false)
+		cmdCtx.Integrity, running.LoadConfig)
```
Comment (oleg-jukovec) [inline cli/instances/list.go:34]: Skip

File: cli/replicaset/rebootstrap.go [hunk 18]
```diff
@@ -60,7 +60,7 @@ func cleanDataFiles(instCtx running.InstanceCtx) error {
 // and starting it again.
 func Rebootstrap(cmdCtx cmdcontext.CmdCtx, cliOpts config.CliOpts, rbCtx RebootstrapCtx) error {
 	apps, err := running.CollectInstancesForApps([]string{rbCtx.AppName}, &cliOpts,
-		cmdCtx.Cli.ConfigDir, cmdCtx.Integrity, true)
+		cmdCtx.Cli.ConfigDir, cmdCtx.Integrity, running.SkipConfig)
```
Comment (oleg-jukovec) [inline cli/replicaset/rebootstrap.go:63]: Load.

File: cli/running/running_test.go [hunk 19]
```diff
@@ -35,7 +35,7 @@ func Test_CollectInstances(t *testing.T) {
 	instances, err := CollectInstances("script", instancesEnabledPath,
 		integrity.IntegrityCtx{
 			Repository: &mockRepository{},
-		}, true)
+		}, LoadConfig)
```
Comment (oleg-jukovec) [inline cli/running/running_test.go:38]: Tests with a new functionality are missed.

Comment (patapenka-alexey) [reply cli/running/running_test.go]: Added.

File: cli/running/running_test.go [hunk 20]
```diff
@@ -113,18 +113,32 @@ func Test_CollectInstances(t *testing.T) {
...
+		}, ConfigLoadSkip)
+	assert.NoError(t, err)
+	assert.Equal(t, 1, len(instances))
+	// Skip instance script searching error.
+	instances, err = CollectInstances("script", instancesEnabledPath,
+		integrity.IntegrityCtx{
+			Repository: &mockRepository{},
+		}, ConfigLoadCluster)
+	assert.NoError(t, err)
+	assert.Equal(t, 1, len(instances))
```
Comment (oleg-jukovec) [inline cli/running/running_test.go:141]: Please, add it as a separate tests. It's better to have 5 independent tests that a one big.

File: cli/running/running.go [hunk 21]
```diff
@@ -126,6 +126,17 @@ type providerImpl struct {
 	instanceCtx *InstanceCtx
 }
 
+type ConfigLoad int
+
+const (
+	// Skip loading cluster config and instances scripts.
+	ConfigLoadSkip ConfigLoad = iota
+	// Cluster configuration is required.
```
Comment (oleg-jukovec) [inline cli/running/running.go:134]:
```suggestion
	// Cluster configuration is required, trigger an error if not. Instances scripts could be omitted.
```

File: cli/running/running.go [hunk 22]
```diff
@@ -126,6 +126,17 @@ type providerImpl struct {
 	instanceCtx *InstanceCtx
 }
 
+type ConfigLoad int
+
+const (
+	// Skip loading cluster config and instances scripts.
```
Comment (oleg-jukovec) [inline cli/running/running.go:132]: You still load config even ConfigLoadSkip == true.

**Review by oleg-jukovec — CHANGES_REQUESTED** [review]
You are still loading config even ConfigLoadSkip == true.

**Review by oleg-jukovec — APPROVED** [review]

**Review by oleg-jukovec — APPROVED** [review]
Ok, let's merge it now. And left the proper code for the future refactoring. Please, update tests (see a comment above).

**Review by dmyger — APPROVED** [review]

File: cli/running/running_test.go [hunk 23]
```diff
@@ -113,20 +113,87 @@ func Test_CollectInstances(t *testing.T) {
...
+		integrity.IntegrityCtx{
+			Repository: &mockRepository{},
+		}, ConfigLoadCluster)
+	assert.ErrorContains(t, err, "unable to connect to etcd")
+
+	_, err = CollectInstances("config_load", instancesEnabledPath,
+		integrity.IntegrityCtx{
+			Repository: &mockRepository{},
+		}, ConfigLoadSkip)
+	assert.NoError(t, err)
```
Comment (oleg-jukovec) [inline cli/running/running_test.go:194]: Such tests are better to test with a table tests approach: https://go.dev/wiki/TableDrivenTests
```suggestion
	cases := []struct {
		mode ConfigLoad
		err      string
	} {
		{
			mode: ConfigLoadAll,
			err:     "unable to connect to etcd",
		},
		{
			mode: ConfigLoadCluster,
			err:     "unable to connect to etcd",
		},
		{
			mode: ConfigLoadSkip,
		},
	}

	for _, tc := cases {
		t.Run(t.err, func(t *testing.T) {
			_, err := CollectInstances("config_load", instancesEnabledPath,
				integrity.IntegrityCtx{
					Repository: &mockRepository{},
				}, tc.mode)
			if tc.err != "" {
				assert.ErrorContains(t, err, tc.err)
			} else {
				assert.NoError(t, err)
			}
		})
	}
```

File: cli/running/running_test.go [hunk 24]
```diff
@@ -113,20 +113,87 @@ func Test_CollectInstances(t *testing.T) {
...
 		integrity.IntegrityCtx{
 			Repository: &mockRepository{},
-		}, true)
+		}, ConfigLoadAll)
 	assert.ErrorContains(t, err, "script.lua: permission denied")
 	assert.Equal(t, 1, len(instances))
 	require.NoError(t, os.Chmod(instancesEnabledPath, 0755))
 }
 
+func Test_CollectInstancesInstanceScript(t *testing.T) {
```
Comment (oleg-jukovec) [inline cli/running/running_test.go:130]: The same: we need a table-driven approach or multiple test cases here.

**Comment by oleg-jukovec** [comment]
Please, rebase on the master branch to fix the CI.

File: cli/pack/opts.go [hunk 25]
```diff
@@ -49,7 +49,7 @@ func initAppsInfo(cliOpts *config.CliOpts, cmdCtx *cmdcontext.CmdCtx, packCtx *P
 	}
 	packCtx.AppList = appList
 	packCtx.AppsInfo, err = running.CollectInstancesForApps(packCtx.AppList, cliOpts,
-		cmdCtx.Cli.ConfigDir, cmdCtx.Integrity, true)
+		cmdCtx.Cli.ConfigDir, cmdCtx.Integrity, running.ConfigLoadSkip)
```
Comment (elhimov) [inline cli/pack/opts.go:52]: It seems this is the place where the instances scripts are required while cluster config is optional, but there is no corresponding enum value for that. If we pack multi-instance application and instance script is missing we will successfully pack it w/o the script and this is wrong.

**Review by oleg-jukovec — APPROVED** [review]

File: cli/pack/opts.go (hunk 25 above)
Comment (patapenka-alexey) [reply cli/pack/opts.go]: I removed it cause didn't find the place to use this value. Thanks, updated.

**Review by oleg-jukovec — APPROVED** [review]

File: cli/running/running.go [hunk 26]
```diff
@@ -126,6 +126,21 @@ type providerImpl struct {
 	instanceCtx *InstanceCtx
 }
 
+type ConfigLoad int
```
Comment (oleg-jukovec) [inline cli/running/running.go:129]: A commit is missed.

**Review by elhimov — APPROVED** [review]
Thanks for the patch! LGTM.
