### PR TITLE
formatter: fix rendering of empty maps

### LINKED ISSUE #1102: `tt connect` Panic on render empty table with `table/ttable` output format
```>\set output table```
```>{}```

https://github.com/tarantool/tt/blob/f13b13e8f7813e1e95765e8c3e93fdd27380bbca/cli/formatter/table.go#L286

```
whoops! It looks like something is wrong with this version of Tarantool CLI.
Error: Unhandled internal error: runtime error: index out of range [0] with length 0
Version: Tarantool CLI version 2.7.0, linux/amd64. commit: f13b13e
Stacktrace:
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.22.11/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/tarantool/tt/cli/util.InternalError({0x1502cad, 0x1c}, 0xc0000d89a8?, {0xc0000d8960, 0x1, 0x1})
	/home/runner/work/tt/tt/cli/util/util.go:140 +0x98
main.main.func1()
	/home/runner/work/tt/tt/cli/main.go:18 +0x5a
panic({0x145f580?, 0xc00003a0a8?})
	/opt/hostedtoolcache/go/1.22.11/x64/src/runtime/panic.go:770 +0x132
github.com/tarantool/tt/cli/formatter.renderEqualMaps({0x0, 0x0, 0xc0000d8c68?}, 0x0, {0xc0?, 0xc000012150?, 0xc0004b0fe0?})
	/home/runner/work/tt/tt/cli/formatter/table.go:286 +0x885
github.com/tarantool/tt/cli/formatter.renderArraysAsTable({0x211ac80?, 0x18?, 0x194?}, 0x0, {0x80?, 0x10?, 0x10?})
	/home/runner/work/tt/tt/cli/formatter/table.go:181 +0x23f
github.com/tarantool/tt/cli/formatter.renderArrays({0xc0004b1010?, 0x130dac0?, 0x2?}, 0x10?, {0x10?, 0xc0000d8e00?, 0x41d0d8?})
	/home/runner/work/tt/tt/cli/formatter/table.go:149 +0x85
github.com/tarantool/tt/cli/formatter.renderBatch({0xc0004b1010?, 0xc0004b1010?, 0xc0000d8ef8?}, 0xfe?, {0x10?, 0x135a9e0?, 0x20b1401?})
	/home/runner/work/tt/tt/cli/formatter/table.go:404 +0x8f1
github.com/tarantool/tt/cli/formatter.renderBatches({0xc0000121b0?, 0xc0004b0fe0?, 0x1?}, 0x0, {0xe0?, 0xc0004b0ef0?, 0x30?})
	/home/runner/work/tt/tt/cli/formatter/table.go:415 +0x7b
github.com/tarantool/tt/cli/formatter.makeTableOutput({0xc0000141d0?, 0xc00011b500?}, 0x0, {0x90?, 0x131ece0?, 0x67b36c01?})
	/home/runner/work/tt/tt/cli/formatter/table.go:543 +0xaad
github.com/tarantool/tt/cli/formatter.MakeOutput(0x1656f60?, {0xc0000141d0?, 0x130cb40?}, {0x30?, 0x0?, 0xc00011b500?})
	/home/runner/work/tt/tt/cli/formatter/format.go:71 +0x89
github.com/tarantool/tt/cli/connect.getExecutor.func1({0xc0005ca022, 0x2})
	/home/runner/work/tt/tt/cli/connect/console.go:267 +0x533
github.com/tarantool/go-prompt.(*Prompt).Run(0xc0001ad400)
	/home/runner/go/pkg/mod/github.com/tarantool/go-prompt@v1.0.1/prompt.go:156 +0x667
github.com/tarantool/tt/cli/connect.(*Console).Run(0xc0005162c0)
	/home/runner/work/tt/tt/cli/connect/console.go:172 +0x196
github.com/tarantool/tt/cli/connect.runConsole({{0x14e2418, 0x4}, {0x7ffdb7940d7d, 0x32}, {0x0, 0x0}, {0x0, 0x0}, {{0x0, 0x0}, ...}}, ...)
	/home/runner/work/tt/tt/cli/connect/connect.go:156 +0x133
github.com/tarantool/tt/cli/connect.Connect({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}, ...}, ...)
	/home/runner/work/tt/tt/cli/connect/connect.go:83 +0x67
github.com/tarantool/tt/cli/cmd.internalConnectModule(0x20b0280, {0xc000045a30, 0x1, 0x1})
	/home/runner/work/tt/tt/cli/cmd/connect.go:240 +0x458
github.com/tarantool/tt/cli/modules.RunCmd(0x20b0280, {0xc000015940, 0xa}, 0x91f797d00000000?, 0x1656290, {0xc000045a30, 0x1, 0x1})
	/home/runner/work/tt/tt/cli/modules/run.go:36 +0xb2
github.com/tarantool/tt/cli/cmd.NewConnectCmd.func1(0xc000608008, {0xc000045a30, 0x1, 0x1})
	/home/runner/work/tt/tt/cli/cmd/connect.go:66 +0x94
github.com/spf13/cobra.(*Command).execute(0xc000608008, {0xc000118230, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005f8308)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/tarantool/tt/cli/cmd.Execute()
	/home/runner/work/tt/tt/cli/cmd/root.go:213 +0x1e
main.main()
	/home/runner/work/tt/tt/cli/main.go:23 +0x35
```

### PR DESCRIPTION
**Pull request by patapenka-alexey**
Closes #1102

### CODE REVIEW

File: cli/formatter/table.go [hunk 1]
```diff
@@ -283,9 +283,11 @@ func renderEqualMaps(maps []unorderedMap[any], transpose bool, opts Opts) (strin
...
 
 	var commonKeys []any
-	maps[0].forEach(func(mapKey, _ any) {
-		commonKeys = append(commonKeys, mapKey)
-	})
+	if len(maps) > 0 {
+		maps[0].forEach(func(mapKey, _ any) {
+			commonKeys = append(commonKeys, mapKey)
+		})
+	}
```
Comment (oleg-jukovec) [inline cli/formatter/table.go:290]: It will be obvious:
```suggestion
	if item, ok := maps[0]; ok {
		item.forEach(func(mapKey, _ any) {
			commonKeys = append(commonKeys, mapKey)
		})
	}
```

File: cli/formatter/table.go [hunk 2]
```diff
@@ -283,9 +283,11 @@ func renderEqualMaps(maps []unorderedMap[any], transpose bool, opts Opts) (strin
 	t := newTableWriter(opts)
 
 	var commonKeys []any
-	maps[0].forEach(func(mapKey, _ any) {
-		commonKeys = append(commonKeys, mapKey)
-	})
+	if len(maps) > 0 {
+		maps[0].forEach(func(mapKey, _ any) {
```
Comment (oleg-jukovec) [inline cli/formatter/table.go:287]: Why is `maps[0]` is used here? Is it a some idea behind it?

File: cli/formatter/format_test.go [hunk 3]
```diff
@@ -311,6 +311,15 @@ func TestFormatter_MakeOutputFormat(t *testing.T) {
 			"",
 			true,
 		},
+		{
+			// when user typed to console:
+			// localhost:xxxx> \set output table
+			// localhost:xxxx> {}
+			formatter.TableFormat,
+			"{}",
+			"+------+\n| col1 |\n+------+\n|      |\n+------+\n",
```
Comment (oleg-jukovec) [inline cli/formatter/format_test.go:320]: To be honest, this doesn't look like a correct output. There shouldn't be any table here.

File: cli/formatter/table.go (hunk 1 above)
Comment (d-enk) [reply cli/formatter/table.go:290]: `maps` is a slice

File: cli/formatter/table.go [hunk 4]
```diff
@@ -162,23 +162,27 @@ func renderArraysAsTable(batch []any, transpose bool, opts Opts) (string, error)
...
-	for _, item := range batch {
-		item := item.([]any)
-		itemMap := createUnorderedMap[any](maxLen)
-
-		for i := 0; i < maxLen; i++ {
-			if i < len(item) {
-				itemMap.insert(strconv.Itoa(i+1), item[i])
-			} else {
-				itemMap.insert(strconv.Itoa(i+1), "")
+	if maxLen > 0 {
```
Comment (d-enk) [inline cli/formatter/table.go:165]:
```suggestion
	if maxLen == 0 {
		return "", nil
	}
```

File: cli/formatter/format_test.go [hunk 5]
```diff
@@ -311,6 +311,15 @@ func TestFormatter_MakeOutputFormat(t *testing.T) {
...
 		},
+		{
+			// when user typed to console:
+			// localhost:xxxx> \set output table
+			// localhost:xxxx> {}
+			formatter.TableFormat,
+			"{}",
+			"\n",
+			false,
+		},
```
Comment (oleg-jukovec) [inline cli/formatter/format_test.go:322]: Please, add tests with {}, {}; {{}}; {{}, {}}

**Review by AlexandrLitkevich — APPROVED** [review]

File: cli/formatter/table.go (hunk 4 above)
Comment (patapenka-alexey) [reply cli/formatter/table.go]: Ooops. Thanks!

**Review by oleg-jukovec — APPROVED** [review]

**Review by dmyger — APPROVED** [review]
