### PR TITLE
integrity: consider 'instances.enabled' directory

### LINKED ISSUE #1220: install: failed to install tarantool with --use-docker
OS: Ubuntu 24.04

Actual:
Below command failed
./tt install tarantool --use-docker

Expected:
Command is completed successfully.

### LINKED ISSUE #1221: test: need stable `test_install_tarantool_in_docker`
Actual:

Current version of `test_install_tarantool_in_docker` doesn't specify version of tarantool to be installed explicitly. In this case `tt` tries to install the latest one and it means that test "input" may vary and thus it becomes less predictable. This kind of test is suitable for monitoring general consistency but doesn't fit the "release" suite.

Expected:

Introduce test that check installation of the specific tarantool versions.

### LINKED ISSUE #1222: install: failed to install tarantool by commit hash
Actual:
```bash
$ tt install tarantool 4472d924
   • Searching in commits...  
   ⨯ 4472d924: unable to get hash info
```

Expected:
Tarantool should be installed successfully, similar to the following installation by tag (2.10.8 refers to that exact commit):
```bash
$ tt install tarantool 2.10.8
   • Searching in versions... 
   • Checking existing...     
   • Installing tarantool=2.10.8
   • Checking dependencies... 
   • Downloading tarantool... 
   • Patching tarantool...    
   • Building tarantool...    
   • Copying executable...    
   • Copying headers...       
   • Tarantool executable is installed to: "/opt/tarantool/bin/tarantool_2.10.8"
   • Changing symlinks...     
   • Made default by symlink "/opt/tarantool/include/include/tarantool"
   • Use the following command to add the bin_dir directory to the PATH: . <(tt env)
   • Done.
```

### PR DESCRIPTION
**Pull request by elhimov**
Adjust API of integrity library which is common for CE/EE. It doesn't affect functionality of CE at all, but is needed to implement lack of functionality in EE.

Also there were failing test and it is resolved into a bunch of problems that appeared mostly with `tt install tarantool`. All the discovered problems were resolved and included into this PR (in separate commits).

I didn't forget about:

- [x] Well-written commit messages (see [documentation][how-to-write-commit] how to write a commit message)

Related issues:

Part of TNTP-5214
Closes #1220
Closes #1221 
Closes #1222 
Related to tarantool/tarantool#12167

[go-doc]: https://go.dev/blog/godoc
[go-testing]: https://pkg.go.dev/testing
[how-to-write-commit]: https://www.tarantool.io/en/doc/latest/contributing/developer_guidelines/#how-to-write-a-commit-message
[keepachangelog]: https://keepachangelog.com/en/1.0.0/
[tarantoolbot-example]: https://github.com/tarantool/tt/pull/1030/commits

### CODE REVIEW

File: lib/integrity/integrity.go [hunk 1]
```diff
@@ -44,7 +44,9 @@ func RegisterIntegrityCheckFlag(flagset *pflag.FlagSet, dst *string) {}
 func RegisterIntegrityCheckPeriodFlag(flagset *pflag.FlagSet, dst *int) {}
 
 // InitializeIntegrityCheck is a noop setup of integrity checking.
-func InitializeIntegrityCheck(publicKeyPath, configDir string) (IntegrityCtx, error) {
+func InitializeIntegrityCheck(
+	publicKeyPath, configDir, instancesEnabledDir string,
```
Comment (patapenka-alexey) [inline lib/integrity/integrity.go:48]: Discussed with @elhimov.
