### PR TITLE
running: avoid starting an already running instance

### LINKED ISSUE #451: tt status does not show correct instances statuses
Steps to reproduce:
```
$ ../../tt/tt start app1
   • Starting an instance [app1:router-0]...
   • Starting an instance [app1:master-1-1]...
   • Starting an instance [app1:replica-1-1]...
   • Starting an instance [app1:master-2-1]...
   • Starting an instance [app1:replica-2-2]...
   • Starting an instance [app1:stateboard]...
$ ../../tt/tt status app1
   • app1:router-0: RUNNING. PID: 12141.
   • app1:master-1-1: RUNNING. PID: 12142.
   • app1:replica-1-1: RUNNING. PID: 12143.
   • app1:master-2-1: RUNNING. PID: 12144.
   • app1:replica-2-2: RUNNING. PID: 12145.
   • app1:stateboard: RUNNING. PID: 12150.
$ ../../tt/tt stop app1:master-1-1
   • The Instance app1:master-1-1 (PID = 12142) has been terminated.
$ ../../tt/tt status app1
   • app1:replica-1-1: RUNNING. PID: 12143.
   • app1:master-2-1: RUNNING. PID: 12144.
   • app1:replica-2-2: RUNNING. PID: 12145.
   • app1:stateboard: RUNNING. PID: 12150.
   • app1:router-0: RUNNING. PID: 12141.
   • app1:master-1-1: NOT RUNNING
$ ../../tt/tt start app1
   • Starting an instance [app1:master-2-1]...
   • Starting an instance [app1:replica-2-2]...
   • Starting an instance [app1:stateboard]...
   • Starting an instance [app1:router-0]...
   • Starting an instance [app1:master-1-1]...
   • Starting an instance [app1:replica-1-1]...
$ ../../tt/tt status app1
   • app1:router-0: NOT RUNNING
   • app1:master-1-1: RUNNING. PID: 12288.
   • app1:replica-1-1: NOT RUNNING
   • app1:master-2-1: NOT RUNNING
   • app1:replica-2-2: NOT RUNNING
   • app1:stateboard: NOT RUNNING
```
tarantool processes are alive. But `status` shows them as stopped.

### PR DESCRIPTION
**Pull request by vr009**
Before this patch, starting an already running instance did not stop the existing process. 
As a result, the PID file of the existing process was being overwritten by the new start command. 
This led to the situation where it was impossible to control the old process, as the new one was already started. 
Additionally, if the old instance had allocated a port, the new process was unable to allocate it again and failed without the possibility of reallocation without manual killing of the existing process.

Closes #451

### CODE REVIEW

File: cli/cmd/start.go [hunk 1]
```diff
@@ -55,6 +56,15 @@ func internalStartModule(cmdCtx *cmdcontext.CmdCtx, args []string) error {
 		}
 		for _, run := range runningCtx.Instances {
 			appName := running.GetAppInstanceName(run)
+			// If an instance is already running we don't try to start it again.
```
Comment (psergee) [inline cli/cmd/start.go:59]:
```suggestion
			// If an instance is already running don't try to start it again.
```

**Review by psergee — APPROVED** [review]

File: cli/cmd/start.go (hunk 1 above)
Comment (vr009) [reply cli/cmd/start.go]: Fixed.
