### PR TITLE
test: add cleanup for tmp before configure test

### LINKED ISSUE #52: unit tests fails if file /tmp/tt exists
Steps to reproduce:

``` sh
$ echo 'test' > /tmp/tt
$ mage unit            
Running unit tests...
fatal: No names found, cannot describe anything.
?   	github.com/tarantool/tt/cli	[no test files]
?   	github.com/tarantool/tt/cli/cmd	[no test files]
?   	github.com/tarantool/tt/cli/cmdcontext	[no test files]
?   	github.com/tarantool/tt/cli/codegen	[no test files]
--- FAIL: TestConfigureCli (0.00s)
    configure_test.go:50: 
        	Error Trace:	configure_test.go:50
        	Error:      	Expected nil, but got: 0x8
        	Test:       	TestConfigureCli
    configure_test.go:72: 
        	Error Trace:	configure_test.go:72
        	Error:      	Expected nil, but got: 0x8
        	Test:       	TestConfigureCli
FAIL
FAIL	github.com/tarantool/tt/cli/configure	0.002s
?   	github.com/tarantool/tt/cli/modules	[no test files]
?   	github.com/tarantool/tt/cli/rocks	[no test files]
ok  	github.com/tarantool/tt/cli/running	(cached)
ok  	github.com/tarantool/tt/cli/ttlog	(cached)
?   	github.com/tarantool/tt/cli/util	[no test files]
?   	github.com/tarantool/tt/cli/version	[no test files]
FAIL
Error: running "go test ./cli/..." failed with exit code 1
```

### PR DESCRIPTION
**Pull request by better0fdead**
Before testing configure, file "tt" is being deleted
from tmp if it exists.

Close #52

### CODE REVIEW

File: cli/configure/configure_test.go [hunk 1]
```diff
@@ -18,6 +18,12 @@ func TestConfigureCli(t *testing.T) {
 
 	cmdCtx := cmdcontext.CmdCtx{}
 
+	// Remove tt file from tmp if it exists.
```
Comment (LeonidVas) [inline cli/configure/configure_test.go:21]: Hmm, this is not so good because the file may have been created by some other user/service/... and it's bad practice to delete files in tests that were not created while the test was running.
I propose you a better way.
* Run the test in the newly created temporary directory in `\tmp` (`\tmp\some_random_name`)
* Remove the directory in [cleanup](https://pkg.go.dev/testing#T.Cleanup)

**Review by LeonidVas — CHANGES_REQUESTED** [review]
Hi! Thank you for the patch.
Commit message:
Close #52 -> Closes #52

File: cli/configure/configure_test.go (hunk 1 above)
Comment (better0fdead) [reply cli/configure/configure_test.go]: Fixed, now test creates temp dir  and after cleanups it.

File: cli/configure/configure_test.go [hunk 2]
```diff
@@ -30,12 +37,15 @@ func TestConfigureCli(t *testing.T) {
 	// we run `go test`, which compiles the functions again.
 	assert.Equal(cmdCtx.Cli.ConfigPath, "tarantool.yaml")
 
+	testDir, err := ioutil.TempDir(os.TempDir(), "tarantool_test")
```
Comment (0x501D) [inline cli/configure/configure_test.go:40]: Nit: ioutil.TempDir(os.TempDir(), "tarantool_tt_")

File: cli/configure/configure_test.go [hunk 3]
```diff
@@ -12,6 +12,13 @@ import (
 	"github.com/tarantool/tt/cli/util"
 )
 
+// Cleanup temp directory after test.
+func cleanupTempDir(tempDir string) {
+	if _, err := os.Stat(tempDir); !os.IsNotExist(err) {
+		os.Remove(tempDir)
```
Comment (0x501D) [inline cli/configure/configure_test.go:18]: os.RemoveAll

File: cli/configure/configure_test.go (hunk 2 above)
Comment (better0fdead) [reply cli/configure/configure_test.go]: fixed

File: cli/configure/configure_test.go (hunk 3 above)
Comment (better0fdead) [reply cli/configure/configure_test.go]: fixed

File: cli/configure/configure_test.go [hunk 4]
```diff
@@ -12,6 +12,13 @@ import (
 	"github.com/tarantool/tt/cli/util"
 )
 
+// Cleanup temp directory after test.
```
Comment (LeonidVas) [inline cli/configure/configure_test.go:15]: https://go.dev/blog/godoc
> Notice this comment is a complete sentence that **begins with the name of the element it describes**.

**Review by LeonidVas — COMMENTED** [review]
Hi!
The commit message line should be less than 72 (see https://github.com/tarantool/tarantool/wiki/Code-review-procedure#commit-message), not 36.

File: cli/configure/configure_test.go (hunk 4 above)
Comment (better0fdead) [reply cli/configure/configure_test.go]: Fixed
