### PR TITLE
uninstall: fix uninstalling if no symlink in bin_dir

### LINKED ISSUE #900: `tt uninstall` does not work if no symlink in `bin_dir`
How to reproduce:
```
$ ls -l bin/
total 22512
-rwxr-xr-x. 1 user user 23048344 Jul 10 16:44 tt_94ba971

$ tt uninstall tt 94ba971
   • Removing binary...       
   ⨯ failed to resolve symlink /home/user/tmp/bin/tt: lstat /home/user/tmp/bin/tt: no such file or directory
```

### PR DESCRIPTION
**Pull request by elhimov**
Closes #900

### CODE REVIEW

**Comment by elhimov** [comment]
Original PR - #997 (unable to update it as it has been made in fork)

File: cli/uninstall/uninstall.go [hunk 1]
```diff
@@ -61,19 +61,29 @@ func remove(program string, programVersion string, directory string,
...
+		if !os.IsNotExist(err) {
+			return false, fmt.Errorf("failed to access %q: %s", linkPath, err)
+		}
+		isSymlinkRemoved = false
+	} else {
+		// Get path where symlink point.
+		resolvedPath, err := util.ResolveSymlink(linkPath)
 		if err != nil {
-			return false, err
+			return false, fmt.Errorf("failed to resolve symlink %q: %s", linkPath, err)
```
Comment (oleg-jukovec) [inline cli/uninstall/uninstall.go:77]:
```suggestion
			return false, fmt.Errorf("failed to resolve symlink %q: %w", linkPath, err)
```

File: cli/uninstall/uninstall.go [hunk 2]
```diff
@@ -61,19 +61,29 @@ func remove(program string, programVersion string, directory string,
...
+
 	var isSymlinkRemoved bool
-	// Remove symlink if it points to program.
-	if strings.Contains(resolvedPath, fileName) {
-		err = os.Remove(linkPath)
+
+	_, err = os.Lstat(linkPath)
+	if err != nil {
+		if !os.IsNotExist(err) {
+			return false, fmt.Errorf("failed to access %q: %s", linkPath, err)
```
Comment (oleg-jukovec) [inline cli/uninstall/uninstall.go:70]:
```suggestion
			return false, fmt.Errorf("failed to access %q: %w", linkPath, err)
```

File: cli/uninstall/uninstall.go (hunk 1 above)
Comment (elhimov) [reply cli/uninstall/uninstall.go]: Fixed.

File: cli/uninstall/uninstall.go (hunk 2 above)
Comment (elhimov) [reply cli/uninstall/uninstall.go]: Fixed

File: test/integration/uninstall/test_uninstall.py [hunk 3]
```diff
@@ -348,3 +348,23 @@ def test_uninstall_tt_missing_version_character(
...
+    symlink_path = os.path.join(tmp_path, 'tt')
+    assert not os.path.exists(symlink_path)
+
+    uninstall_cmd = [tt_cmd, "uninstall", "tt", "94ba971"]
+    uninstall_rc, uninstall_output = run_command_and_get_output(uninstall_cmd, cwd=tmp_path)
+
+    assert uninstall_rc == 0
+    assert "tt=94ba971 is uninstalled." in uninstall_output
+
+    assert os.path.exists(os.path.join(tmp_path, "tt_" + "94ba971") is False)
```
Comment (patapenka-alexey) [inline test/integration/uninstall/test_uninstall.py:370]:
```suggestion
    assert os.path.exists(os.path.join(tmp_path, "tt_94ba971") is False)
```
Up to you.

**Review by dmyger — APPROVED** [review]
