### PR TITLE
connect: fix terminal after executing os.exit()

### LINKED ISSUE #425: terminal session is broken after os.exit() in tt connect session
### Steps to reproduce:

Terminal 1:
```
$ tarantool
tarantool> box.cfg{listen=3301}
tarantool> box.schema.user.create("user", { password = "password", if_not_exists = true })
tarantool> box.schema.user.grant("user", "super", nil, nil, { if_not_exists = true })
```

Terminal 2:

```
[0] ~$ tt connect 127.0.0.1:3301 -u user -p password
   • Connecting to the instance...
   • Connected to 127.0.0.1:3301

127.0.0.1:3301> os.exit()
```

### Actual results

Terminal session is broken after closing connection in `tt connect` - typed symbols are invisible. Workaround - type `reset` and press Enter.

```
   ⨯ Connection was closed. Probably instance process isn't running anymore
<terminal session is broken here>
[0] ~$ 
```

It is worth to note that exit by Ctrl-D doesn't break console.

### Expected results

Terminal session is usable after closing connection in `tt connect`.

### Environment

Tarantool 2.11.0-rc2-0-g2ae0c94a2
`tt version`: Tarantool CLI version 1.0.1, linux/amd64. commit: e11e945
OS: Ubuntu 22.04 amd64
Terminal emulator: XTerm 372

### PR DESCRIPTION
**Pull request by better0fdead**
Fixed terminal brake after os.exit() in tt connect session. Have done it by adding workaround for the bug(c-bata/go-prompt#228) in case of executing os.exit().

Proof:

Terminal 1:
```
tarantool> better0fdead@better0fdead:~/.local/share/Trash$ tarantool
Tarantool 2.11.0-entrypoint-635-g5a38c5c90
type 'help' for interactive help
tarantool> box.cfg{listen=3305}
2023-04-27 12:44:48.029 [34240] main/103/interactive I> Tarantool 2.11.0-entrypoint-635-g5a38c5c90
2023-04-27 12:44:48.029 [34240] main/103/interactive I> log level 5
2023-04-27 12:44:48.030 [34240] main/103/interactive I> wal/engine cleanup is paused
2023-04-27 12:44:48.030 [34240] main/103/interactive I> mapping 268435456 bytes for memtx tuple arena...
2023-04-27 12:44:48.030 [34240] main/103/interactive I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274
2023-04-27 12:44:48.030 [34240] main/103/interactive I> mapping 134217728 bytes for vinyl tuple arena...
2023-04-27 12:44:48.034 [34240] main/103/interactive I> Recovering snapshot with schema version 2.11.0
2023-04-27 12:44:48.043 [34240] main/103/interactive I> update replication_synchro_quorum = 1
2023-04-27 12:44:48.043 [34240] main/103/interactive I> instance uuid 7a61e056-9b15-4c30-b6a1-f0110ea030aa
2023-04-27 12:44:48.044 [34240] main/103/interactive I> instance vclock {1: 5}
2023-04-27 12:44:48.044 [34240] main/103/interactive I> tx_binary: bound to 0.0.0.0:3305
2023-04-27 12:44:48.044 [34240] main/103/interactive I> recovery start
2023-04-27 12:44:48.044 [34240] main/103/interactive I> recovering from `./00000000000000000000.snap'
2023-04-27 12:44:48.057 [34240] main/103/interactive I> cluster uuid f0bd4cd7-d6df-42d0-8a9c-930cd9727f65
2023-04-27 12:44:48.065 [34240] main/103/interactive I> assigned id 1 to replica 7a61e056-9b15-4c30-b6a1-f0110ea030aa
2023-04-27 12:44:48.065 [34240] main/103/interactive I> update replication_synchro_quorum = 1
2023-04-27 12:44:48.065 [34240] main/103/interactive I> recover from `./00000000000000000000.xlog'
2023-04-27 12:44:48.065 [34240] main/103/interactive I> done `./00000000000000000000.xlog'
2023-04-27 12:44:48.065 [34240] main/103/interactive I> recover from `./00000000000000000005.xlog'
2023-04-27 12:44:48.065 [34240] main/103/interactive I> done `./00000000000000000005.xlog'
2023-04-27 12:44:48.066 [34240] main/103/interactive I> ready to accept requests
2023-04-27 12:44:48.066 [34240] main/103/interactive I> leaving orphan mode
2023-04-27 12:44:48.066 [34240] main/104/gc I> wal/engine cleanup is resumed
2023-04-27 12:44:48.066 [34240] main/103/interactive I> set 'listen' configuration option to 3305
2023-04-27 12:44:48.066 [34240] main/103/interactive I> set 'log_level' configuration option to 5
2023-04-27 12:44:48.066 [34240] main/103/interactive I> set 'log_format' configuration option to "plain"
---
...

2023-04-27 12:44:48.066 [34240] main/105/checkpoint_daemon I> scheduled next checkpoint for Thu Apr 27 14:20:21 2023
tarantool> box.schema.user.create("user", { password = "password", if_not_exists = true })
---
...

tarantool> box.schema.user.grant("user", "super", nil, nil, { if_not_exists = true })
---
...

2023-04-27 12:45:10.627 [34240] main/114/iproto.shutdown I> tx_binary: stopped
2023-04-27 12:45:13.619 [34240] main/102/on_shutdown fiber.c:642 E> TimedOut: timed out
2023-04-27 12:45:13.619 [34240] main/102/on_shutdown main.cc:157 E> on_shutdown triggers failed
2023-04-27 12:45:13.620 [34240] main/102/on_shutdown trigger.cc:251 E> TimedOut: timed out

```

Terminal 2:

```
better0fdead@better0fdead:~/tt$ ./tt connect 127.0.0.1:3305 -u user -p password
   • Connecting to the instance...
   • Connected to 127.0.0.1:3305

127.0.0.1:3305> os.exit()
   ⨯ Connection was closed. Probably instance process isn't running anymore
better0fdead@better0fdead:~/tt$ ps
    PID TTY          TIME CMD
  33829 pts/1    00:00:00 bash
  34276 pts/1    00:00:00 ps

```

Closes #425

### CODE REVIEW

File: cli/connect/console.go [hunk 1]
```diff
@@ -247,6 +247,14 @@ func getExecutor(console *Console) prompt.Executor {
 		var data string
 		if _, err := console.conn.Eval(consoleEvalFuncBody, args, opts); err != nil {
 			if err == io.EOF {
+				if strings.Contains(console.input, "os.exit(") {
```
Comment (psergee) [inline cli/connect/console.go:250]: Should we check the reason of EOF? Or it is okay to run the command below always? `os.exit` can be invoked using alias, or pcall, which will not be handled correctly.

File: cli/connect/console.go [hunk 2]
```diff
@@ -247,6 +247,14 @@ func getExecutor(console *Console) prompt.Executor {
...
+					console.Close()
```
Comment (LeonidVas) [inline cli/connect/console.go:251]: I haven't dug deep, but the same problem has already been fixed in https://github.com/tarantool/tt/commit/f1111a928dca63641f99db3b358ca91dec2769ac .
Maybe we should
- move the code fixing the console into a separate function
- call it from `console.close()`.

**Review by LeonidVas — CHANGES_REQUESTED** [review]
Hi! Thank you for the patch.
See a comment bellow.

File: cli/connect/console.go (hunk 1 above)
Comment (better0fdead) [reply cli/connect/console.go]: Rewrote. I think it should be fine to not check the reason of EOF.

File: cli/connect/console.go (hunk 2 above)
Comment (better0fdead) [reply cli/connect/console.go]: https://github.com/tarantool/tt/commit/f1111a928dca63641f99db3b358ca91dec2769ac  Doesn't fix it. Moved code

**Review by psergee — APPROVED** [review]

**Review by LeonidVas — APPROVED** [review]
