### PR TITLE
help: fix output

### LINKED ISSUE #320: Broken help for all commands
```
./tt version --help
Show Tarantool CLI version information

USAGE
EXTERNAL COMMANDS
  No available external commands
```
Usage is empty.
EXTERNAL COMMANDS makes no sense for most tt commands.

### PR DESCRIPTION
**Pull request by better0fdead**
Usage is now shown for all commands.
External commands is now not shown for commands without it.

Example with external command: 
```  
Utility for managing Tarantool packages and Tarantool-based applications

USAGE
  tt [flags] <command> [command flags]

COMMANDS
  build       Build an application in specified PATH (default ".")
...
  version     Show Tarantool CLI version information
 
EXTERNAL COMMANDS
  help	Description for external module help
List of passed args: --description

FLAGS
  -c, --cfg string     Path to configuration file
...
  -V, --verbose        Verbose output

EXAMPLES
  $ tt version -L /path/to/local/dir
  $ tt help -S -I
  $ tt completion

Use "tt <command> --help" for more information about a command.
``` 

Example without external command: 
``` 
Utility for managing Tarantool packages and Tarantool-based applications

USAGE
  tt [flags] <command> [command flags]

COMMANDS
  build       Build an application in specified PATH (default ".")
...
  version     Show Tarantool CLI version information
 
FLAGS
  -c, --cfg string     Path to configuration file
...
  -V, --verbose        Verbose output

EXAMPLES
  $ tt version -L /path/to/local/dir
  $ tt help -S -I
  $ tt completion

Use "tt <command> --help" for more information about a command.
``` 

Closes #320

### CODE REVIEW

File: cli/cmd/help.go [hunk 1]
```diff
@@ -22,7 +22,12 @@ type DefaultHelpFunc func(*cobra.Command, []string)
 // (for example `tt help version`), we try to get the help from it.
 func configureHelpCommand(cmdCtx *cmdcontext.CmdCtx, rootCmd *cobra.Command) error {
 	// Add information about external modules into help template.
-	rootCmd.SetUsageTemplate(fmt.Sprintf(usageTemplate, getExternalCommandsString(&modulesInfo)))
+	if getExternalCommandsString(&modulesInfo) != "  No available external commands" {
```
Comment (psergee) [inline cli/cmd/help.go:25]: Why don't you use constant from help package for the comparison?

File: cli/cmd/help.go [hunk 2]
```diff
@@ -22,7 +22,12 @@ type DefaultHelpFunc func(*cobra.Command, []string)
...
+		rootCmd.SetUsageTemplate(fmt.Sprintf(usageTemplateWithExternal,
+			getExternalCommandsString(&modulesInfo)))
```
Comment (psergee) [inline cli/cmd/help.go:27]: So, we call `getExternalCommandsString`, which loops over modules map, twice. Why?

File: cli/cmd/help.go [hunk 3]
```diff
@@ -171,6 +180,50 @@ Usage: {{ .Cmd }}
   {{.Example}}
 {{end -}}
 
+{{- if .HasAvailableSubCommands}}
+Use "{{.CommandPath}} <command> --help" for more information about a command.
+{{end -}}
+`
+
+	usageTemplateWithoutExternal = util.Bold("USAGE") + `
```
Comment (psergee) [inline cli/cmd/help.go:188]: As I can see, these usage templates are almost the same. The only difference is external commands descriptions. Please, remove duplication.

File: cli/cmd/help.go (hunk 2 above)
Comment (better0fdead) [reply cli/cmd/help.go]: changed

File: cli/cmd/help.go (hunk 3 above)
Comment (better0fdead) [reply cli/cmd/help.go]: Removed

File: cli/cmd/help.go [hunk 4]
```diff
@@ -114,10 +115,11 @@ func getExternalCommandsString(modulesInfo *modules.ModulesInfo) string {
 	}
 
 	if str != "" {
+		str = util.Bold("\nEXTERNAL COMMANDS\n") + str
 		return str[:len(str)-1]
 	}
 
-	return fmt.Sprintf("  %s", noAvailableExternalCmdMsg)
+	return fmt.Sprintf("")
```
Comment (psergee) [inline cli/cmd/help.go:122]: Why do we need Sprintf for an empty string?

File: cli/cmd/help.go [hunk 5]
```diff
@@ -114,10 +115,11 @@ func getExternalCommandsString(modulesInfo *modules.ModulesInfo) string {
 	}
 
 	if str != "" {
+		str = util.Bold("\nEXTERNAL COMMANDS\n") + str
 		return str[:len(str)-1]
```
Comment (psergee) [inline cli/cmd/help.go:119]: What is the purpose of `:len(str)-1`? Can we use Trim instead?

File: cli/cmd/help.go [hunk 6]
```diff
@@ -23,6 +23,7 @@ type DefaultHelpFunc func(*cobra.Command, []string)
 func configureHelpCommand(cmdCtx *cmdcontext.CmdCtx, rootCmd *cobra.Command) error {
 	// Add information about external modules into help template.
 	rootCmd.SetUsageTemplate(fmt.Sprintf(usageTemplate, getExternalCommandsString(&modulesInfo)))
+
```
Comment (psergee) [inline cli/cmd/help.go:26]: Not related to the fix.

File: cli/cmd/help.go [hunk 7]
```diff
@@ -155,8 +161,7 @@ Usage: {{ .Cmd }}
 {{end}}
 {{end -}}
 
-{{- if not .HasAvailableInheritedFlags}}` + util.Bold("\nEXTERNAL COMMANDS") + `
-%s
+{{- if not .HasAvailableInheritedFlags}} %s
```
Comment (psergee) [inline cli/cmd/help.go:164]: Please add an examples of the help output to the PR description. So, we can see it's format with external command and without.

File: cli/cmd/help.go (hunk 4 above)
Comment (better0fdead) [reply cli/cmd/help.go]: Removed

File: cli/cmd/help.go (hunk 5 above)
Comment (better0fdead) [reply cli/cmd/help.go]: Replaced

File: cli/cmd/help.go (hunk 6 above)
Comment (better0fdead) [reply cli/cmd/help.go]: Removed

File: cli/cmd/help.go (hunk 7 above)
Comment (better0fdead) [reply cli/cmd/help.go:161]: Added example to PR message

**Review by psergee — APPROVED** [review]
