### PR TITLE
launcher: fix stdout buffering

### LINKED ISSUE #36: Fix the problem with the log write
When a new instance of tarantool is started in `instance.go`, by default the log will be written with block buffering. The `stdbuf` utility was used to change this behavior, but it is not installed on macOS by default. Needs to investigate the problem and implement a universal solution.
```
// Start starts the Instance with the specified parameters.
func (inst *Instance) Start() error {
  // By default (when using "glibc") "stdout" is line buffered when connected
  // to a TTY and block buffered (one page 4KB) when connected to a pipe / file.
  // This is not how we want to log work, so set "stdout" to line buffered mode
  // by using "stdbuf" utility. "strderr" is set to no-buffering by default.
  //
  // Several useful links:
  // https://www.pixelbeat.org/programming/stdio_buffering/
  // https://man7.org/linux/man-pages/man3/setbuf.3.html
  // https://github.com/coreutils/coreutils/blob/master/src/stdbuf.c
  inst.Cmd = exec.Command("stdbuf", "-o", "L",
    inst.tarantoolPath, "-e", instanceLauncher)
  inst.Cmd.Stdout = inst.logger.Writer()
  inst.Cmd.Stderr = inst.logger.Writer()
  inst.Cmd.Env = append(os.Environ(), "TT_CLI_INSTANCE="+inst.appPath)
  inst.Cmd.Env = append(inst.Cmd.Env,
    "TT_CLI_CONSOLE_SOCKET="+inst.consoleSocket)

  // Imitate the "tarantoolctl".
  inst.Cmd.Env = append(inst.Cmd.Env, "TARANTOOLCTL=true")
  // Set the sign that the program is running under "tt".
  inst.Cmd.Env = append(inst.Cmd.Env, "TT_CLI=true")

  // Start an Instance.
  if err := inst.Cmd.Start(); err != nil {
    return err
  }
  inst.done = false

  return nil
}
```

Note that the original problem may have been misunderstood by the author.

### PR DESCRIPTION
**Pull request by 0x501D**
This patch enables linebuffering for stdout fstream.

Closes #36

### CODE REVIEW

**Comment by 0x501D** [comment]
This patch was tested with:
* gentoo (glibc)
* alpine (musl)
* macosx

File: cli/running/lua/launcher.lua [hunk 1]
```diff
@@ -20,6 +21,32 @@ local function start_instance()
         __defer_update = true
     }
 
+    -- Make stdout linebuffered. gh-36.
+    -- By default (when using "glibc") "stdout" is line buffered when connected
+    -- to a TTY and block buffered (one page 4KB) when connected to a pipe / file.
+    -- This is not how we want to log work, so set "stdout" to line buffered mode
```
Comment (Totktonada) [inline cli/running/lua/launcher.lua:27]: It is not about log, but about `print()` in Lua, see https://github.com/tarantool/tt/issues/36#issuecomment-1106915036.

File: cli/running/lua/launcher.lua [hunk 2]
```diff
@@ -20,6 +21,32 @@ local function start_instance()
...
+    -- by calling "setlinebuf(3)". "strderr" is set to no-buffering by default.
```
Comment (Totktonada) [inline cli/running/lua/launcher.lua:28]: Typo: strderr -> stderr.

File: cli/running/lua/launcher.lua (hunk 1 above)
Comment (0x501D) [reply cli/running/lua/launcher.lua]: Comment rewritten.

File: cli/running/lua/launcher.lua (hunk 2 above)
Comment (0x501D) [reply cli/running/lua/launcher.lua]: Fixed

**Review by LeonidVas — APPROVED** [review]
