### PR TITLE
cmd: add config check for almost all commands

### LINKED ISSUE #371: Check all commands for an ability to work without a config
Most of `tt` command shouldn't work without environment configuration. Need to check for config file existence. For example `tt status` does not work without tt.yaml:
```
$ tt  status
   ⨯ tt.yaml not found
```
But `tt install` does:
```
$ tt install tarantool
   • Getting latest tarantool version..
   • Checking existing...     
```

### PR DESCRIPTION
**Pull request by oleg-jukovec**
The check has been added for:

- binaries
- build
- check
- clean
- create
- install
- instances
- logrotate
- pack
- restart
- run
- start
- status
- stop
- uninstall

Closes #371

The patch does not affect:

-  cartridge
-  cat
-  cfg
-  completion
-  connect
-  coredump
-  daemon
-  help
-  init
-  play
-  rocks 
-  search
-  version

I'm not sure about the command list. I suggest to add commands in a review.

### CODE REVIEW

File: cli/cmd/common.go [hunk 1]
```diff
@@ -22,3 +23,13 @@ func handleCmdErr(cmd *cobra.Command, err error) {
 		log.Fatalf(err.Error())
 	}
 }
+
+var errNoConfig = errors.New("tt.yaml not found, you need to create tt" +
+	" environment config with tt init")
+
+func checkConfig(cmdCtx *cmdcontext.CmdCtx) error {
```
Comment (better0fdead) [inline cli/cmd/common.go:30]: i would like to see small description to function

File: cli/cmd/common.go [hunk 2]
```diff
@@ -22,3 +23,13 @@ func handleCmdErr(cmd *cobra.Command, err error) {
 		log.Fatalf(err.Error())
 	}
 }
+
+var errNoConfig = errors.New("tt.yaml not found, you need to create tt" +
+	" environment config with tt init")
```
Comment (better0fdead) [inline cli/cmd/common.go:28]:
```suggestion
	" environment config with 'tt init'")
```
up to you, i think it looks better to highlight commands in (').

**Comment by better0fdead** [comment]
Thx for patch, just small comments. I think commit title should be:
```cmd: add config check for almost commands```=>```cmd: add config check for almost all commands```

File: cli/cmd/common.go (hunk 1 above)
Comment (oleg-jukovec) [reply cli/cmd/common.go:32]: Added.

File: cli/cmd/common.go (hunk 2 above)
Comment (oleg-jukovec) [reply cli/cmd/common.go]: Thank you, updated.

**Comment by oleg-jukovec** [comment]
> `cmd: add config check for almost commands`=>`cmd: add config check for almost all commands`

Thank you, updated.

**Review by better0fdead — APPROVED** [review]

File: cli/cmd/common.go [hunk 3]
```diff
@@ -22,3 +23,15 @@ func handleCmdErr(cmd *cobra.Command, err error) {
 		log.Fatalf(err.Error())
 	}
 }
+
+// errNoConfig is returned if environment config file tt.yaml not found.
+var errNoConfig = errors.New("tt.yaml not found, you need to create tt" +
```
Comment (psergee) [inline cli/cmd/common.go:28]: Let's use ConfigName from the `configure` package instead of `tt.yaml`.

File: cli/cmd/common.go [hunk 4]
```diff
@@ -22,3 +23,15 @@ func handleCmdErr(cmd *cobra.Command, err error) {
...
+	" environment config with 'tt init'")
```
Comment (psergee) [inline cli/cmd/common.go:29]: " or provide exact config location with `--cfg` option" :)

File: cli/cmd/common.go [hunk 5]
```diff
@@ -22,3 +23,15 @@ func handleCmdErr(cmd *cobra.Command, err error) {
...
+
+// checkConfig returns an error if environment config file tt.yaml not found.
+func checkConfig(cmdCtx *cmdcontext.CmdCtx) error {
```
Comment (psergee) [inline cli/cmd/common.go:32]: It is not clear from the function name what it does. Can we have something like "[is]ConfigFound" or "[is]ConfigFileLoaded" returning bool instead of error?

Comment (oleg-jukovec) [reply cli/cmd/common.go]: I've renamed `checkConfig` -> `checkConfigExist`.

It looks easier:

```Go
if err != checkConfigExist(ctx); err != nil {
    return err
}
```

Than:

```Go
if ok != isConfigExist(ctx); !ok {
    return someErr
}
```

for me. But I can redo it if you insist.

File: cli/cmd/common.go (hunk 3 above)
Comment (oleg-jukovec) [reply cli/cmd/common.go]: Thank you, updated.

File: cli/cmd/common.go (hunk 4 above)
Comment (oleg-jukovec) [reply cli/cmd/common.go]: Added.

File: cli/cmd/common.go (hunk 5 above)
Comment (psergee) [reply cli/cmd/common.go]: What do you think about 
```go
if !configExists(ctx) {
    . . . 
}
```
?
Errors are mostly used for exceptional cases. Missing config does not look exceptional for `exists` kind of functions.
But this is for sure exceptional for start command implementation, for example.

**Review by psergee — APPROVED** [review]

**Comment by psergee** [comment]
Suppose, we need to check for config in 
connect. to be able to connect using instances names
logrotate. command accepts app name. Where will it search for app log without config?

**Comment by psergee** [comment]
- Update changelog.
- Add a comment with list of the commands which work without a config file.

**Comment by oleg-jukovec** [comment]
> Suppose, we need to check for config in logrotate. command accepts app name. Where will it search for app log without config?

I've added the check for logrotate.

> Update changelog.

Done.

> Add a comment with list of the commands which work without a config file.

I've updated the pull request message. Did you mean to add a comment somewhere else?

File: CHANGELOG.md [hunk 6]
```diff
@@ -40,6 +40,8 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
 - tt config is renamed to tt.yaml.
 - Do not use `make` command options for `tarantool` build if `MAKEFLAGS` environment variable
 is set.
+- `binaries`, `build`, `check`, `clean`, `create`, `install`, `instances`, `logrotate`, `pack`,
+  `restart`, `run`, `start`, `stop`, `uninstall` require environment configuration file.
```
Comment (psergee) [inline CHANGELOG.md:44]:
```suggestion
  `restart`, `run`, `start`, `status`, `stop`, `uninstall` require environment configuration file.
```

Comment (oleg-jukovec) [reply CHANGELOG.md]: Fixed.

**Review by psergee — APPROVED** [review]
