### PR TITLE
tt: fix returning status code on unsuccessful dependency install

### LINKED ISSUE #651: install exits with code 0 on fail
```bash
$ ~/src/tt/tt install tt master
   • Checking existing...     
   • Installing tt=master     
   • Checking dependencies... 
   ⨯ The operation requires some dependencies.
Missing packages:  mage
Usage: tt install -f if you already have those packages installed
$ echo $?
0
```

It makes really hard to debug CI which uses tt in this case.

### PR DESCRIPTION
**Pull request by themilchenko**
Fixed a bug related with case when program finishes with 0 status code in unsuccessful way.
To do this I edit returning type from `bool` to `error` in `programDependenciesInstalled` function to finish program with error exit code in right way on higher layer.

Closes #651

### CODE REVIEW

File: cli/install/install.go [hunk 1]
```diff
@@ -196,7 +197,8 @@ func detectOsName() (string, error) {
 
 // getVersionsFromRepo returns all available versions from github repository.
 func getVersionsFromRepo(local bool, distfiles string, program string,
-	repolink string) ([]version.Version, error) {
+	repolink string,
+) ([]version.Version, error) {
```
Comment (oleg-jukovec) [inline cli/install/install.go:201]: We don't need this unnecessary changes. Especially in the commit.

Please, revert all unnecessary/code-style changes unrelated to the issue. This only makes it more difficult to view the change history without any value. Changes in code style must be accepted for the entire project and covered by a linter.

File: cli/install/install.go [hunk 2]
```diff
@@ -281,33 +284,47 @@ func isPackageInstalled(packageName string) bool {
...
 		} else if strings.Contains(osName, "CentOs") {
-			programs = []Package{{"cmake", "cmake"}, {"git", "git"}, {"make", "make"},
-				{"gcc", "gcc"}, {"g++", "gcc-c++ "}}
+			programs = []Package{
+				{"cmake", "cmake"},
+				{"git", "git"},
+				{"make", "make"},
+				{"gcc", "gcc"},
+				{"g++", "gcc-c++ "},
+			}
```
Comment (oleg-jukovec) [inline cli/install/install.go:317]: The same.

File: cli/install/install.go [hunk 3]
```diff
@@ -384,7 +409,8 @@ func downloadRepo(repoLink string, tag string, dst string, logFile *os.File, ver
 
 // copyBuildedTT copies tt binary.
 func copyBuildedTT(binDir, path, version string, installCtx InstallCtx,
-	logFile *os.File) error {
+	logFile *os.File,
+) error {
```
Comment (oleg-jukovec) [inline cli/install/install.go:413]: And below.

**Review by oleg-jukovec — CHANGES_REQUESTED** [review]
Please, update the commit message according to the rules:
https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message

and revert all unnecessary/code-style changes.

File: cli/install/install.go [hunk 4]
```diff
@@ -281,7 +281,7 @@ func isPackageInstalled(packageName string) bool {
 }
 
 // programDependenciesInstalled checks if dependencies are installed.
-func programDependenciesInstalled(program string) bool {
+func programDependenciesInstalled(program string) error {
```
Comment (psergee) [inline cli/install/install.go:284]: The function name + the return type became confusing. "error" should be used if something goes wrong with the dependencies checking.

File: cli/install/install.go [hunk 5]
```diff
@@ -304,10 +304,10 @@ func programDependenciesInstalled(program string) bool {
 				" are installed.\n"+
 				"Proceed without checking?")
 			if !answer || err != nil {
-				return false
+				return err
```
Comment (psergee) [inline cli/install/install.go:307]: Suppose this will return nil and we will continue installation. Which is not what a user expects.

**Review by psergee — COMMENTED** [review]
Thank you for the patch. See my comments below.
Please add a note to the 'fixed' section in change log also.

File: cli/install/install.go (hunk 4 above)
Comment (themilchenko) [reply cli/install/install.go]: Have changed it to `(bool, error)`. So now function name corresponds to the return value and the error occurs when something goes wrong with dependencies checking and goes on higher layers of program to correctly finish a program.

File: cli/install/install.go (hunk 5 above)
Comment (themilchenko) [reply cli/install/install.go]: Fixed it. Returning `false, error` allows to handle it using bool type and return error if it was occured.

File: cli/install/install.go [hunk 6]
```diff
@@ -304,10 +304,10 @@ func programDependenciesInstalled(program string) bool {
 				" are installed.\n"+
 				"Proceed without checking?")
 			if !answer || err != nil {
-				return false
+				return false, err
```
Comment (oleg-jukovec) [inline cli/install/install.go:307]: It could be reasonable to return an error status code in the case too:

```
$ sudo pacman -S firefox
resolving dependencies...
looking for conflicting packages...

Packages (1) firefox-127.0.1-1

Total Download Size:    69.04 MiB
Total Installed Size:  240.98 MiB
Net Upgrade Size:        1.45 MiB

:: Proceed with installation? [Y/n] n
$ echo $?
1
```

File: cli/util/errors.go [hunk 7]
```diff
@@ -0,0 +1,7 @@
+package util
+
+import "errors"
+
+var (
+	ErrCmdAbort = errors.New("abort")
```
Comment (psergee) [inline cli/util/errors.go:6]: Simple "abort" reminds me about sigabrt and `abort()` call. Let' use "aborted by user" error text.

Comment (themilchenko) [reply cli/util/errors.go]: Fixed.

File: test/integration/install/test_install.py [hunk 8]
```diff
@@ -614,3 +615,43 @@ def test_install_tt_already_exists_with_symlink(tt_cmd, tmpdir):
...
+
+
+@pytest.mark.parametrize("package_to_exclude, expected_rc", [
+    pytest.param(
+        "mage",
+        1,
+    ),
+    pytest.param(
+        "",
+        0,
```
Comment (psergee) [inline test/integration/install/test_install.py:627]: There are integration tests, which test `tt` installation - test/integration/install/test_install.py.

File: test/integration/install/test_install.py [hunk 9]
```diff
@@ -614,3 +615,43 @@ def test_install_tt_already_exists_with_symlink(tt_cmd, tmpdir):
...
+    )
+])
+def test_install_tt_exit_code_dependency_check(
+        tt_cmd,
+        tmpdir,
+        package_to_exclude,
+        expected_rc):
+    # Create new PATH with excluded packages
```
Comment (psergee) [inline test/integration/install/test_install.py:635]:
```suggestion
    # Create new PATH with excluded packages.
```

File: test/integration/install/test_install.py [hunk 10]
```diff
@@ -614,3 +615,43 @@ def test_install_tt_already_exists_with_symlink(tt_cmd, tmpdir):
...
+    original_path = os.environ['PATH']
+    new_path_elements = []
+    for dir in original_path.split(os.pathsep):
+        if os.path.isdir(dir) and package_to_exclude not in os.listdir(dir):
+            new_path_elements.append(dir)
+    new_path = os.pathsep.join(new_path_elements)
+
+    with mock.patch.dict(os.environ, {'PATH': new_path}):
+        configPath = os.path.join(tmpdir, config_name)
+        # Create test config
```
Comment (oleg-jukovec) [inline test/integration/install/test_install.py:645]:
```suggestion
        # Create test config.
```

File: test/integration/install/test_install.py [hunk 11]
```diff
@@ -614,3 +615,43 @@ def test_install_tt_already_exists_with_symlink(tt_cmd, tmpdir):
...
+        expected_rc):
+    # Create new PATH with excluded packages
+    original_path = os.environ['PATH']
+    new_path_elements = []
+    for dir in original_path.split(os.pathsep):
+        if os.path.isdir(dir) and package_to_exclude not in os.listdir(dir):
+            new_path_elements.append(dir)
+    new_path = os.pathsep.join(new_path_elements)
+
+    with mock.patch.dict(os.environ, {'PATH': new_path}):
```
Comment (psergee) [inline test/integration/install/test_install.py:643]: No need patch existing env and restore it after `with`, just pass the new env to the `subprocess.Popen` call.

File: test/integration/install/test_install.py [hunk 12]
```diff
@@ -614,3 +615,43 @@ def test_install_tt_already_exists_with_symlink(tt_cmd, tmpdir):
...
+        tmpdir,
+        package_to_exclude,
+        expected_rc):
+    # Create new PATH with excluded packages
+    original_path = os.environ['PATH']
+    new_path_elements = []
+    for dir in original_path.split(os.pathsep):
+        if os.path.isdir(dir) and package_to_exclude not in os.listdir(dir):
+            new_path_elements.append(dir)
+    new_path = os.pathsep.join(new_path_elements)
```
Comment (psergee) [inline test/integration/install/test_install.py:641]: Jus a suggestion
```suggestion
new_path = os.pathsep.join(filter(lambda dir: os.path.isdir(dir) and exe not in os.listdir(dir),
                                                     original_path.split(os.pathsep)))
```

File: test/integration/install/test_install.py (hunk 8 above)
Comment (themilchenko) [reply test/integration/install/test_install.py]: Just deleted it. Also change test to check only excluded dependencies cause successful one we have in `test_tt_install` function.

File: test/integration/install/test_install.py (hunk 9 above)
Comment (themilchenko) [reply test/integration/install/test_install.py]: Added.

File: test/integration/install/test_install.py (hunk 10 above)
Comment (themilchenko) [reply test/integration/install/test_install.py]: Added.

File: test/integration/install/test_install.py (hunk 11 above)
Comment (themilchenko) [reply test/integration/install/test_install.py]: Changed it.

File: test/integration/install/test_install.py (hunk 12 above)
Comment (themilchenko) [reply test/integration/install/test_install.py]: Changed too.

File: cli/util/errors.go [hunk 13]
```diff
@@ -0,0 +1,7 @@
+package util
+
+import "errors"
+
+var (
+	ErrCmdAbort = errors.New("aborted by user")
```
Comment (psergee) [inline cli/util/errors.go:6]: Need comments for all external functions, vars, consts, types...

Comment (themilchenko) [reply cli/util/errors.go:7]: Added comment for this error.

**Review by psergee — APPROVED** [review]
lgtm

**Review by oleg-jukovec — APPROVED** [review]
Thank you for the patch!

**Comment by oleg-jukovec** [comment]
Please, rebase to the master branch and resolve conflicts.
