### PR TITLE
install: add the ability to flexibly define the version

### LINKED ISSUE #737: Ability to install a <major>.<minor> version of tarantool
Currently as I can see there is only a possibility to install an exact version of Tarantool, specifying `<major>.<minor>.<patch>`, like `2.11.2`. 
It'll be great to have an ability to install tarantool of a latest available `<major>.<minor>` version, like you can do with pyenv for example:
```
pyenv install 3.12
```

Right now tt results in an error:
```
tt install tarantool 2.11
   • Searching in commits...
   ⨯ the hash must contain at least 7 characters
```

### PR DESCRIPTION
**Pull request by dmyger**
Allow specify version like:
 - 2.11 - Chooses last release patch for specified major.minor set
 - 3 - get last available release version with required major==3
 - 2.11-rc - will select in major.minor version with last release candidate mark
 And many other combination matched with version regular expression.

Closes #737

### CODE REVIEW

File: cli/version/version_tools.go [hunk 1]
```diff
@@ -73,28 +73,40 @@ type Version struct {
 	BuildName  string  // Custom build name.
 }
 
-// Parse parses a version string and return the version value it represents.
-func Parse(verStr string) (Version, error) {
-	version := Version{}
-	var err error
-
-	// Part 1 (optional) -> custom build name,
+func createVersionRegexp(is_strict bool) *regexp.Regexp {
```
Comment (oleg-jukovec) [inline cli/version/version_tools.go:76]: camelCase for variable names only.
```suggestion
func createVersionRegexp(isStrict bool) *regexp.Regexp {
```

File: cli/install/install_test.go [hunk 2]
```diff
@@ -11,6 +12,15 @@ import (
...
 )
 
+func parseVersion(verStr []string) []version.Version {
+	versions := make([]version.Version, 0, len(verStr))
+	for _, v := range verStr {
+		ver, _ := version.Parse(v)
+		versions = append(versions, ver)
+	}
+	return versions
+}
```
Comment (oleg-jukovec) [inline cli/install/install_test.go:22]:
```suggestion
func parseVersion(t testing.TB, verStr []string) []version.Version {
	t.Helper()

	versions := make([]version.Version, 0, len(verStr))
	for _, v := range verStr {
		ver, err := version.Parse(v)
		require.NoError(t, err)
		versions = append(versions, ver)
	}
	return versions
}
```

File: cli/version/version_match_test.go [hunk 3]
```diff
@@ -0,0 +1,235 @@
+package version
```
Comment (oleg-jukovec) [inline cli/version/version_match_test.go:1]: I understand that the rules are broken in the `tt` from time to time, but it is better to test only the public API. At least for a new code.

```suggestion
package version_test
```

File: cli/version/version_tools.go [hunk 4]
```diff
@@ -73,28 +73,40 @@ type Version struct {
...
+		`(?:-(?P<release>entrypoint|rc|alpha|beta)(?P<releaseNum>\d+)?)?` +
+		`(?:-(?P<additional>\d+))?` +
+		`(?:-(?P<hash>g[a-f0-9]+))?(?:-r(?P<revision>\d+))?(-gc64|-nogc64)?$`
+	if !is_strict {
+		matchString = strings.Replace(matchString, "{1}", "?", 3)
+	}
+	return regexp.MustCompile(matchString)
+}
+
+func matchVersionParts(version string, is_strict bool) (map[string]string, error) {
```
Comment (oleg-jukovec) [inline cli/version/version_tools.go:95]:
```suggestion
func matchVersionParts(version string, isStrict bool) (map[string]string, error) {
```

File: cli/uninstall/uninstall_test.go [hunk 5]
```diff
@@ -145,7 +145,7 @@ func TestSearchLatestVersion(t *testing.T) {
 	}
 }
 
-func TestGetAllVersionFormats(t *testing.T) {
+func Test_getAllVersionFormats(t *testing.T) {
```
Comment (oleg-jukovec) [inline cli/uninstall/uninstall_test.go:148]: If you make such changes, then apply them at least for the entire file, and even better for the package.
```suggestion
func TestGetAllVersionFormats(t *testing.T) {
```

File: cli/version/version_match.go [hunk 6]
```diff
@@ -0,0 +1,156 @@
...
+		version.Release, err = newRelease(matches["release"], matches["releaseNum"])
+		if err != nil {
+			return version, fmt.Errorf("can't parse Release; %s", err)
+		}
+		version.requiredFields = append(version.requiredFields, CompareMatchReleaseType)
+		if matches["releaseNum"] != "" {
+			version.requiredFields = append(version.requiredFields, CompareMatchReleaseNum)
+		}
+	} else if len(version.requiredFields) > 0 {
+		// By default require 'release' version
```
Comment (oleg-jukovec) [inline cli/version/version_match.go:97]:
```suggestion
		// By default require 'release' version.
```

File: cli/version/version_match.go [hunk 7]
```diff
@@ -0,0 +1,156 @@
...
+	}
+
+	version.BuildName = matches["buildname"]
+	if version.BuildName != "" {
+		version.requiredFields = append(version.requiredFields, CompareMatchBuildName)
+	}
+
+	if matches["major"] != "" {
+		if version.Major, err = util.AtoiUint64(matches["major"]); err != nil {
+			return version, fmt.Errorf("can't parse Major; %s", err)
```
Comment (oleg-jukovec) [inline cli/version/version_match.go:68]: The usual error wrapping looks like this:
```suggestion
			return version, fmt.Errorf("can't parse Major: %w", err)
```

File: cli/version/version_match.go [hunk 8]
```diff
@@ -0,0 +1,156 @@
...
+)
+
+const (
+	IgnoredVersionPart = ^uint64(0)
+)
+
+type CompareResult uint16
+
+const (
+	// Values according order of Fields in regex from `matchVersionParts()`
```
Comment (oleg-jukovec) [inline cli/version/version_match.go:16]:
```suggestion
	// Values according order of Fields in regex from `matchVersionParts()`.
```

File: cli/version/version_match.go [hunk 9]
```diff
@@ -0,0 +1,156 @@
...
+	if matches["major"] != "" {
+		if version.Major, err = util.AtoiUint64(matches["major"]); err != nil {
+			return version, fmt.Errorf("can't parse Major; %s", err)
+		}
+		version.requiredFields = append(version.requiredFields, CompareMatchMajor)
+	}
+
+	if matches["minor"] != "" {
+		if version.Minor, err = util.AtoiUint64(matches["minor"]); err != nil {
+			return version, fmt.Errorf("can't parse Minor; %s", err)
```
Comment (oleg-jukovec) [inline cli/version/version_match.go:75]: etc
```suggestion
			return version, fmt.Errorf("can't parse Minor: %w", err)
```

**Review by oleg-jukovec — CHANGES_REQUESTED** [review]
Thank you for the patch, please add a new entry into the `CHANGELOG.md` file.

File: cli/version/version_match.go [hunk 10]
```diff
@@ -0,0 +1,156 @@
...
+	"fmt"
+
+	"github.com/tarantool/tt/cli/util"
+)
+
+const (
+	IgnoredVersionPart = ^uint64(0)
+)
+
+type CompareResult uint16
```
Comment (oleg-jukovec) [inline cli/version/version_match.go:13]: Since it is a public API of the package, it should be a well-commented.

File: cli/version/version_match.go [hunk 11]
```diff
@@ -0,0 +1,156 @@
...
+			Release: Release{
+				Type: TypeRelease,
+				Num:  IgnoredVersionPart,
+			},
+		},
+		requiredFields: make([]CompareResult, 0, CompareMatchTotal),
+	}
+}
+
+func Explore(verStr string) (MatchVersion, error) {
```
Comment (oleg-jukovec) [inline cli/version/version_match.go:53]: Since it is a public API of the package, it should be a well-commented [2] etc.

File: cli/install/install.go [hunk 12]
```diff
@@ -502,28 +514,17 @@ func installTt(binDir string, installCtx InstallCtx, distfiles string) error {
...
-			for _, ver := range versions {
-				if ttVersion == ver.Str || (versionMatches && "v"+ttVersion == ver.Str) {
-					versionFound = true
-					ttVersion = ver.Str
-					break
-				}
-			}
-			if !versionFound {
-				return fmt.Errorf("%s version of tt doesn't exist", ttVersion)
+				return fmt.Errorf("version of tt doesn't exist: %s", err)
```
Comment (themilchenko) [inline cli/install/install.go:527]:
```suggestion
				return fmt.Errorf("version of tt doesn't exist: %w", err)
```

File: cli/install/install.go [hunk 13]
```diff
@@ -1018,22 +1020,18 @@ func installTarantool(binDir string, incDir string, installCtx InstallCtx,
...
-				if tarVersion == ver.Str {
-					versionFound = true
-					break
-				}
-			}
-			if !versionFound {
-				return fmt.Errorf("%s version of tarantool doesn't exist", tarVersion)
+			tarVersion, err = findVersion(versions, expectedVersion)
+			if err != nil {
+				return fmt.Errorf("version of tarantool doesn't exist: %s", err)
```
Comment (themilchenko) [inline cli/install/install.go:1033]:
```suggestion
				return fmt.Errorf("version of tarantool doesn't exist: %w", err)
```

File: cli/version/version_match.go [hunk 14]
```diff
@@ -0,0 +1,156 @@
...
+	if matches["minor"] != "" {
+		if version.Minor, err = util.AtoiUint64(matches["minor"]); err != nil {
+			return version, fmt.Errorf("can't parse Minor; %s", err)
+		}
+		version.requiredFields = append(version.requiredFields, CompareMatchMinor)
+	}
+
+	if matches["patch"] != "" {
+		if version.Patch, err = util.AtoiUint64(matches["patch"]); err != nil {
+			return version, fmt.Errorf("can't parse Patch; %s", err)
```
Comment (themilchenko) [inline cli/version/version_match.go:82]:
```suggestion
			return version, fmt.Errorf("can't parse Patch version: %w", err)
```

File: cli/version/version_match.go [hunk 15]
```diff
@@ -0,0 +1,156 @@
...
+		}
+		version.requiredFields = append(version.requiredFields, CompareMatchPatch)
+	}
+
+	if matches["release"] != "" {
+		version.Release, err = newRelease(matches["release"], matches["releaseNum"])
+		if err != nil {
+			return version, fmt.Errorf("can't parse Release; %s", err)
```
Comment (themilchenko) [inline cli/version/version_match.go:90]:
```suggestion
			return version, fmt.Errorf("can't parse Release tag: %w", err)
```

File: cli/version/version_match.go [hunk 16]
```diff
@@ -0,0 +1,156 @@
...
+	}
+
+	version.Hash = matches["hash"]
+	if version.Hash != "" {
+		version.requiredFields = append(version.requiredFields, CompareMatchHash)
+	}
+
+	if matches["revision"] != "" {
+		if version.Revision, err = util.AtoiUint64(matches["revision"]); err != nil {
+			return version, fmt.Errorf("can't parse Revision; %s", err)
```
Comment (themilchenko) [inline cli/version/version_match.go:115]:
```suggestion
			return version, fmt.Errorf("can't parse Revision: %w", err)
```

File: cli/version/version_match.go [hunk 17]
```diff
@@ -0,0 +1,161 @@
...
+
+const NotFoundVersion = "NOT_FOUND"
+
+// exploreMatchVersion examines the given string and retrieves the version components,
+// that define the rules for checking for version consistency.
+func exploreMatchVersion(verStr string) (Version, requiredFields, error) {
+	var version Version
+	fields := make(requiredFields, 0, countOfRequiredFields)
+
+	matches, err := matchVersionParts(verStr, false)
```
Comment (themilchenko) [inline cli/version/version_match.go:35]: Now I can install version with incorrect name. For example if I try to use versions like `v.2.1`, `.2.1` the output will be:

```bash
$ ./tt install tt v.2.1 
   • Searching in versions... 
   • Checking existing...     
   • Installing tt=v2.2.1     
   • Checking dependencies... 
   • Downloading tt...        
   • Building tt...           
   • Copying executable...    
   • Tt executable is installed to: "/home/milchenko/tarantool/tt/bin/tt_v2.2.1"
   • Made default by symlink "/home/milchenko/tarantool/tt/bin/tt"
   • Use the following command to add the bin_dir directory to the PATH: . <(tt env)
   • Done.    
```

Possibly it can be a feature due to `tt` try to search the latest version by giving pattern even it has incorrect syntax, but in my opinion it is more a bug. Correct me if I'm wrong.

File: test/integration/install/test_install.py [hunk 18]
```diff
@@ -214,6 +215,29 @@ def test_install_tt_specific_version(tt_cmd, tmp_path):
...
 
+@pytest.mark.slow
+def test_install_tt_incomplete_version(tt_cmd, tmp_path):
+    configPath = tmp_path / config_name
+    # Create test config.
+    with open(configPath, "w") as f:
+        f.write("env:\n  bin_dir:\n  inc_dir:\n")
+
+    # Install latest tt.
+    install_cmd = (tt_cmd, "--cfg", configPath, "install", "tt", "2.1")
```
Comment (themilchenko) [inline test/integration/install/test_install.py:226]: I think we can test many different scenarios here with different version formats and errors using `parametrize`.

File: test/integration/install/test_install.py [hunk 19]
```diff
@@ -214,6 +215,29 @@ def test_install_tt_specific_version(tt_cmd, tmp_path):
     assert re.search(r"Tarantool CLI version 2.1.2", start_output)
 
 
+@pytest.mark.slow
+def test_install_tt_incomplete_version(tt_cmd, tmp_path):
```
Comment (themilchenko) [inline test/integration/install/test_install.py:219]: We need the same tests for tarantool installation.

File: cli/version/version_match.go [hunk 20]
```diff
@@ -0,0 +1,161 @@
...
+	}
+
+	version.BuildName = matches["buildname"]
+	if version.BuildName != "" {
+		fields = append(fields, requiredFieldBuildName)
+	}
+
+	if matches["major"] != "" {
+		if version.Major, err = util.AtoiUint64(matches["major"]); err != nil {
+			return version, fields, fmt.Errorf("can't parse Major; %w", err)
```
Comment (themilchenko) [inline cli/version/version_match.go:47]: In my opinion `:` is more prettier than `;` symbol.

Besides, as I have noticed, there is a pattern in `tt` that the error wrapper starts with the error description and is complemented after `:` by the error received.

Or am I missing something and this wrap has a different purpose?

```suggestion
			return version, fields, fmt.Errorf("can't parse Major: %w", err)
```

**Review by themilchenko — COMMENTED** [review]
Please, add note about this feature to the CHANGELOG.

File: cli/version/version_match.go [hunk 21]
```diff
@@ -0,0 +1,161 @@
...
+	requiredFieldReleaseType
+	requiredFieldReleaseNum
+	requiredFieldAdditional
+	requiredFieldHash
+	requiredFieldRevision
+
+	countOfRequiredFields
+)
+
+const NotFoundVersion = "NOT_FOUND"
```
Comment (oleg-jukovec) [inline cli/version/version_match.go:27]: Please, add a comment to the public API constant.

File: cli/version/version_match.go [hunk 22]
```diff
@@ -0,0 +1,161 @@
...
+		}
+		if !isMatch {
+			return false
+		}
+	}
+	return true
+}
+
+// Check is string looks like version.
+// If isStrict is true, then version <major.minor.patch> components are required.
```
Comment (oleg-jukovec) [inline cli/version/version_match.go:139]:
```suggestion
// IsVersion checks is string looks like version.
// If isStrict is true, then version <major.minor.patch> components are required.
```

File: cli/version/version_match.go (hunk 17 above)
Comment (dmyger) [reply cli/version/version_match.go:35]: It seems debatable - what the correct version means.
Here you apply the rule where <major> does not important. And it found first of last version with such match.

If needed, we can set the <major> part as mandatory. But, the best way here should be more interactive behavior of the tool. It should collect all matches and ask user to make a choose.

File: cli/version/version_match.go (hunk 20 above)
Comment (dmyger) [reply cli/version/version_match.go]: Done.

File: test/integration/install/test_install.py (hunk 18 above)
Comment (oleg-jukovec) [reply test/integration/install/test_install.py:226]: `tt install` is a takes much time, so it's ok to test with integration tests some basic scenarios, but remaining scenarios should be tested with lighter tests (unit-tests).

File: cli/version/version_match.go (hunk 17 above)
Comment (oleg-jukovec) [reply cli/version/version_match.go:35]: To be honest, I don't know when such behavior might be useful. So I propose require a major if minor is set, minor if patch is set etc.

File: test/integration/install/test_install.py (hunk 18 above)
Comment (dmyger) [reply test/integration/install/test_install.py:226]: I add another generic case for `tt install tt <version>` because this test works fast enough. 
And used `parametrize` for easy future expansion.

File: cli/version/version_match.go (hunk 17 above)
Comment (dmyger) [reply cli/version/version_match.go:35]: Implement this logic:
- `patch` - requires `minor`
- `minor` - requires `major`

File: cli/version/version_match.go [hunk 23]
```diff
@@ -0,0 +1,161 @@
...
+func IsVersion(version string, isStrict bool) bool {
+	re := createVersionRegexp(isStrict)
+	return re.MatchString(version)
+}
+
+// MatchVersion takes as input an ascending sorted list of versions.
+// In which it finds the latest version matching the search mask.
+//
+// Return string of found version or `NotFoundVersion` with error if just not found
```
[the remark this answers is not in the document]
Comment (dmyger) [reply cli/version/version_match.go]: Done.

File: cli/version/version_match.go [hunk 24]
```diff
@@ -0,0 +1,174 @@
...
+	requiredFieldRevision
+
+	countOfRequiredFields
+)
+
+// NotFoundError is sentinel error for case when required version not found.
+type NotFoundError struct {
+	expected string
+}
+
```
Comment (oleg-jukovec) [inline cli/version/version_match.go:31]: Please, add a comment to the public API method.

File: cli/version/version_match.go [hunk 25]
```diff
@@ -0,0 +1,174 @@
...
+	if err != nil {
+		return "", err
+	}
+	for i := len(sortedVersions) - 1; i >= 0; i-- {
+		ver := sortedVersions[i]
+		if compareVersions(reference, ver, fields) {
+			return ver.Str, nil
+		}
+	}
+	return "", NotFoundError{expected}
```
Comment (oleg-jukovec) [inline cli/version/version_match.go:173]: Please, add a unit-test with the error.

File: cli/version/version_match.go [hunk 26]
```diff
@@ -0,0 +1,174 @@
...
+	if matches["major"] != "" {
+		if version.Major, err = util.AtoiUint64(matches["major"]); err != nil {
+			return version, fields, fmt.Errorf("can't parse Major: %w", err)
+		}
+		fields = append(fields, requiredFieldMajor)
+	}
+
+	if matches["minor"] != "" {
+		if matches["major"] == "" {
+			return version, fields, fmt.Errorf("parse Minor requires Major: %w", err)
```
Comment (themilchenko) [inline cli/version/version_match.go:61]: Something wrong with the output, the error is nil:

```bash
$ ./tt install tt .2.1 
   • Searching in versions... 
   ⨯ parse Minor requires Major: %!!(MISSING)w(<nil>)
```

**Comment by oleg-jukovec** [comment]
Please, rebase to the `master` branch.

File: cli/version/version_match.go [hunk 27]
```diff
@@ -0,0 +1,174 @@
...
+		if version.Minor, err = util.AtoiUint64(matches["minor"]); err != nil {
+			return version, fields, fmt.Errorf("can't parse Minor: %w", err)
+		}
+		fields = append(fields, requiredFieldMinor)
+	}
+
+	if matches["patch"] != "" {
+		if matches["minor"] == "" {
+			return version, fields, fmt.Errorf("parse Patch requires Minor: %w", err)
+		}
```
[the remark this answers is not in the document]
Comment (dmyger) [reply cli/version/version_match.go:72]: Due to the way regex works, this case is not possible. This branch of checks in the code is currently unreachable. It is added only in case regex will changes.

File: cli/version/version_match_test.go [hunk 28]
```diff
@@ -0,0 +1,146 @@
...
+		{"1.1", "", "not matched with: 1.1"},
+		{"3.1-0", "", "not matched with: 3.1-0"},
+		{"V1", "", "failed to parse version"},
+		{"18446744073709551616", "", "can't parse Major"},
+		{"1.18446744073709551616", "", "can't parse Minor"},
+		{"0.1.18446744073709551616", "", "can't parse Patch"},
+		{"1.2.3-rc18446744073709551616", "", "bad release number format"},
+		{"1.2.3-18446744073709551616", "", "can't parse Additional"},
+		{"1.2.3-r18446744073709551616", "", "can't parse Revision"},
+		{".2.3", "", "parse Minor requires Major"},
```
[the remark this answers is not in the document]
Comment (dmyger) [reply cli/version/version_match_test.go:104]: Currently there is no way to specify only `patch`, without `minor`

File: cli/version/version_match.go (hunk 24 above)
Comment (dmyger) [reply cli/version/version_match.go:31]: Added the comment for `Error()` method

File: cli/version/version_match.go (hunk 26 above)
Comment (dmyger) [reply cli/version/version_match.go]: Yeah, here there is no `err` value

File: cli/version/version_match.go (hunk 25 above)
Comment (dmyger) [reply cli/version/version_match.go:174]: Done.

File: cli/version/version_match.go (hunk 27 above)
[the remark this answers is not in the document]
Comment (oleg-jukovec) [reply cli/version/version_match.go]: I think we need a prettier error for the user here. Something like:

```minor version requires major to be specified```

The error looks confusing from a user side. There are too many implementation details that the user will not understand.

File: cli/version/version_match.go [hunk 29]
```diff
@@ -0,0 +1,175 @@
...
+	countOfRequiredFields
+)
+
+// NotFoundError is sentinel error for case when required version not found.
+type NotFoundError struct {
+	expected string
+}
+
+// Error - error interface implementation for NotFoundError.
+func (e NotFoundError) Error() string {
```
Comment (oleg-jukovec) [inline cli/version/version_match.go:33]: Is is usual something like:

https://pkg.go.dev/bytes#Reader.Read
```suggestion
// Error implements the [error] interface.
func (e NotFoundError) Error() string {
```

**Review by oleg-jukovec — APPROVED** [review]

File: cli/version/version_match.go (hunk 27 above)
[the remark this answers is not in the document]
Comment (themilchenko) [reply cli/version/version_match.go]: I catch that this case is not possible. I mean that the error a bit confusing. We type something like `.<patch>` and the output says `parse Minor requires Major`.

File: cli/version/version_match.go (hunk 29 above)
Comment (dmyger) [reply cli/version/version_match.go:33]: Done.

File: cli/version/version_match.go (hunk 27 above)
[the remark this answers is not in the document]
Comment (dmyger) [reply cli/version/version_match.go]: > when we type something like `.<patch>`

We type `.<digit>` and what we put into it nobody knows. In our understanding, it can be either a `.patch` or a `.minor`. But the current regexp considers such input as a `.minor`.

I hope that Oleg's suggestion to change the message will help solve the problem.

[the remark this answers is not in the document]
Comment (themilchenko) [reply cli/version/version_match.go]: Ok, let it be.

**Review by themilchenko — APPROVED** [review]
Thank you for the patch! LGTM.
