### PR TITLE
uninstall: fix removing tt by version

### LINKED ISSUE #583: tt install and uninstall version format is inconsistent
Uninstall does not work with the version specified during installation.
```
$ tt install tt 1.2.0
   • Checking existing...     
   • Installing tt=v1.2.0     
   • Checking dependencies... 
   • Downloading tt...        
   • Building tt...           
   • Copying executable...    
   • Done.                    
$ ls -l bin
total 13232
lrwxrwxrwx 1 user user        9 Aug 29 17:34 tt -> tt_v1.2.0
-rwxrwxr-x 1 user user 13549568 Aug 29 17:34 tt_v1.2.0

$ tt uninstall tt 1.2.0
   • Removing binary...       
   ⨯ there is no tt installed

$ tt uninstall tt v1.2.0
   • Removing binary...       
   • tt=v1.2.0 is uninstalled.
```

### PR DESCRIPTION
**Pull request by themilchenko**
It was impossible to uninstall tt by version without 'v' prefix using `tt unistall tt 1.2.0` for example because program checks version in binary file with prefix.

After the patch `tt uninstall` checks 'v' prefix before version and if it didn't find, adds for strings matching.

Closes #583

### CODE REVIEW

File: cli/uninstall/uninstall.go [hunk 1]
```diff
@@ -111,6 +111,11 @@ func UninstallProgram(program string, programVersion string, binDst string, head
 		if programVersion, err = getDefault(program, binDst); err != nil {
 			return err
 		}
+	} else if program == search.ProgramTt &&
+		strings.Contains(programVersion, ".") && programVersion[0] != 'v' {
```
Comment (oleg-jukovec) [inline cli/uninstall/uninstall.go:115]: https://github.com/tarantool/tt/blob/e90220698092b936858d8ed34b101b0b911fe6a5/cli/install/install.go#L498

For fully symmetry, we need to try to delete two versions (with 'v' and without). Since the `install` could install `1.2.3-xxx-foo-bar` if the tag exist.

File: test/integration/uninstall/test_uninstall.py [hunk 2]
```diff
@@ -306,3 +306,36 @@ def test_uninstall_tarantool_no_switch(tt_cmd, tmp_path):
...
+    # We don't really install it because bug we test
+    # is fixed only for current patch. Due to
+    # binary file is changing while running this
+    # bug won't appear only for current and future versions.
+    shutil.copy(tt_cmd, os.path.join(tmp_path, "tt_v1.2.3"))
+    os.symlink(os.path.join(tmp_path, "tt_v1.2.3"),
+               os.path.join(tmp_path, "tt"))
+
+    # Remove not installed program.
+    uninstall_cmd = [tt_cmd, "--cfg", configPath, "uninstall", "tt", "1.2.3"]
```
Comment (oleg-jukovec) [inline test/integration/uninstall/test_uninstall.py:330]: Please, add a test case with v1.2.3.
```suggestion
    uninstall_cmd = [tt_cmd, "--cfg", configPath, "uninstall", "tt", "1.2.3"]
```

File: cli/uninstall/uninstall.go (hunk 1 above)
Comment (themilchenko) [reply cli/uninstall/uninstall.go:121]: Fixed.

File: test/integration/uninstall/test_uninstall.py (hunk 2 above)
Comment (themilchenko) [reply test/integration/uninstall/test_uninstall.py]: Added.

File: cli/uninstall/uninstall.go [hunk 3]
```diff
@@ -112,12 +112,30 @@ func UninstallProgram(program string, programVersion string, binDst string, head
 			return err
 		}
 	}
+	// We need to try to delete all versions with 'v' prefix before x.y.z version
+	// and without it.
+	versionsToDelete := make([]string, 0, 2)
+	versionsToDelete = append(versionsToDelete, programVersion)
```
Comment (oleg-jukovec) [inline cli/uninstall/uninstall.go:118]: I don't think we need such micro-optimizations here. The code is just harder to read.
```suggestion
	versionsToDelete := []string{programVersion}
```

File: cli/uninstall/uninstall.go [hunk 4]
```diff
@@ -112,12 +112,30 @@ func UninstallProgram(program string, programVersion string, binDst string, head
...
+
+	if program == search.ProgramTt &&
+		strings.Contains(programVersion, ".") && programVersion[0] != 'v' {
+		versionsToDelete = append(versionsToDelete, "v"+programVersion)
+	} else if program == search.ProgramTt &&
+		strings.Contains(programVersion, ".") && programVersion[0] == 'v' {
+		versionsToDelete = append(versionsToDelete, programVersion[1:])
+	}
```
Comment (oleg-jukovec) [inline cli/uninstall/uninstall.go:126]: Nit, tt install does not have such logic.
```suggestion
	}
```

File: cli/uninstall/uninstall.go [hunk 5]
```diff
@@ -112,12 +112,30 @@ func UninstallProgram(program string, programVersion string, binDst string, head
...
 		}
 	}
+	// We need to try to delete all versions with 'v' prefix before x.y.z version
+	// and without it.
+	versionsToDelete := make([]string, 0, 2)
+	versionsToDelete = append(versionsToDelete, programVersion)
+
+	if program == search.ProgramTt &&
+		strings.Contains(programVersion, ".") && programVersion[0] != 'v' {
+		versionsToDelete = append(versionsToDelete, "v"+programVersion)
```
Comment (oleg-jukovec) [inline cli/uninstall/uninstall.go:122]: Please, add a comment why we need the logic here.

**Comment by oleg-jukovec** [comment]
We need a changelog entry too.

File: cli/uninstall/uninstall.go [hunk 6]
```diff
@@ -112,12 +112,30 @@ func UninstallProgram(program string, programVersion string, binDst string, head
 			return err
 		}
 	}
+	// We need to try to delete all versions with 'v' prefix before x.y.z version
+	// and without it.
+	versionsToDelete := make([]string, 0, 2)
+	versionsToDelete = append(versionsToDelete, programVersion)
+
+	if program == search.ProgramTt &&
+		strings.Contains(programVersion, ".") && programVersion[0] != 'v' {
```
Comment (oleg-jukovec) [inline cli/uninstall/uninstall.go:121]:
```suggestion
		programVersion != 'master' && programVersion[0] != 'v' {
```
The `tt install` logic does not contain such checks.

File: cli/uninstall/uninstall.go [hunk 7]
```diff
@@ -112,12 +112,30 @@ func UninstallProgram(program string, programVersion string, binDst string, head
...
+	} else if program == search.ProgramTt &&
+		strings.Contains(programVersion, ".") && programVersion[0] == 'v' {
+		versionsToDelete = append(versionsToDelete, programVersion[1:])
+	}
 
 	var isSymlinkRemoved bool
-	isSymlinkRemoved, err = remove(program, programVersion, binDst, cmdCtx)
+	for _, verToDel := range versionsToDelete {
+		isSymlinkRemoved, err = remove(program, verToDel, binDst, cmdCtx)
+		if err == nil {
```
Comment (psergee) [inline cli/uninstall/uninstall.go:131]: If the first `remove` try failed, the loop continues for the second version string. So, we lost the info about the error occurred.

File: test/integration/uninstall/test_uninstall.py [hunk 8]
```diff
@@ -306,3 +306,44 @@ def test_uninstall_tarantool_no_switch(tt_cmd, tmp_path):
...
+
+    # Copying built executable to bin directory,
+    # renaming it to version and change symlink
+    # to emulate that we have installed it like
+    # tt install tt v1.2.3.
+    # We don't really install it because bug we test
+    # is fixed only for current patch. Due to
+    # binary file is changing while running this
+    # bug won't appear only for current and future versions.
+    shutil.copy(tt_cmd, os.path.join(tmp_path, f"tt_{installed_version}"))
```
Comment (psergee) [inline test/integration/uninstall/test_uninstall.py:333]: Add a test that if there are two versions are installed: v123 and 123
The passed version only will be removed.

File: cli/uninstall/uninstall.go [hunk 9]
```diff
@@ -112,12 +112,30 @@ func UninstallProgram(program string, programVersion string, binDst string, head
 			return err
 		}
 	}
+	// We need to try to delete all versions with 'v' prefix before x.y.z version
```
Comment (psergee) [inline cli/uninstall/uninstall.go:115]: This function is already big enough. Let's extract the code, which decides which versions to be remove to a separate function.

**Review by psergee — COMMENTED** [review]
Thank you for the patch, see my comments below.

File: cli/uninstall/uninstall.go (hunk 6 above)
Comment (themilchenko) [reply cli/uninstall/uninstall.go:121]: What if we have `tt uninstall tt <hash>`? The `programVersion` won't be master and also won't contains 'v' prefix, so it will be `v<hash>` and program won't be uninstalled as it was expected. That is why I want to determine if `programVersion` satisfies the `x.y.z`.

Comment (oleg-jukovec) [reply cli/uninstall/uninstall.go:121]: Than we need the same for `tt install` too. The idea is keep the logic in sync for install and uninstall.

File: test/integration/uninstall/test_uninstall.py (hunk 8 above)
Comment (themilchenko) [reply test/integration/uninstall/test_uninstall.py:333]: How could it be? I thought we can have only one tag version installed using `tt install tt <tag>`: with v tag or without but not both.

File: cli/uninstall/uninstall.go (hunk 4 above)
Comment (themilchenko) [reply cli/uninstall/uninstall.go:126]: Then it won't work for `tt uninstall tt v0.1.0` when file `tt_0.1.0` will exists.

File: cli/uninstall/uninstall.go (hunk 5 above)
Comment (themilchenko) [reply cli/uninstall/uninstall.go]: Added.

File: cli/uninstall/uninstall.go (hunk 7 above)
Comment (themilchenko) [reply cli/uninstall/uninstall.go:127]: Added handling an error excluding case when file was not found.

File: cli/uninstall/uninstall.go (hunk 9 above)
Comment (themilchenko) [reply cli/uninstall/uninstall.go]: Extracted to it's own function.

File: cli/util/errors.go [hunk 10]
```diff
@@ -5,4 +5,8 @@ import "errors"
 var (
 	// ErrCmdAbort is reported when user aborts the program.
 	ErrCmdAbort = errors.New("aborted by user")
+
+	// ErrNoTtInstalled is reported when program cannot find tt binary
+	// file with name provided.
+	ErrNoTtInstalled = errors.New("there is no tt installed")
```
Comment (oleg-jukovec) [inline cli/util/errors.go:11]: This doesn't look like some kind of general-public error so it's better define it on the `uninstall` module level like a private error.

File: cli/uninstall/uninstall.go [hunk 11]
```diff
@@ -113,11 +113,25 @@ func UninstallProgram(program string, programVersion string, binDst string, head
...
+	versionsToDelete := []string{programVersion}
+	if program == search.ProgramTt {
+		versionsToDelete = getAllTtVersionFormats(programVersion)
+	}
+
 	var isSymlinkRemoved bool
-	isSymlinkRemoved, err = remove(program, programVersion, binDst, cmdCtx)
+	for _, verToDel := range versionsToDelete {
+		isSymlinkRemoved, err = remove(program, verToDel, binDst, cmdCtx)
+		if err != nil && err.Error() != util.ErrNoTtInstalled.Error() {
```
Comment (oleg-jukovec) [inline cli/uninstall/uninstall.go:124]:
```suggestion
		if err != nil && !errors.Is(err, ErrNoTtInstalled) {
```

File: cli/uninstall/uninstall.go [hunk 12]
```diff
@@ -133,6 +147,21 @@ func UninstallProgram(program string, programVersion string, binDst string, head
...
 }
 
+// getAllTtVersionFormats returns all version formats with 'v' prefix and
+// without it before x.y.z version.
+func getAllTtVersionFormats(ttVersion string) []string {
+	var versionsToDelete []string
+
+	// Need to determine if we have x.y.z format in tt uninstall argument
+	// to make sure we add version prefix.
+	if strings.Contains(ttVersion, ".") && !strings.HasPrefix(ttVersion, "v") {
```
Comment (oleg-jukovec) [inline cli/uninstall/uninstall.go:157]: The logic still incompatible with the `install`.

`tt install 123` installs 123 if exist or v123 if exist.
`tt uninstall 123` will not uninstall v123.

You need to add the major.minor.patch check with `regexp.Match("^[0-9]+\.[0-9]+\.[0-9]+", ttVersion)` check to the `tt install` in sync with `tt uninstall` or don't add the confusing (`strings.Contains(ttVersion, ".")`) condition here.

File: cli/util/errors.go (hunk 10 above)
Comment (themilchenko) [reply cli/util/errors.go]: Have deleted it and put in uninstall.go as private error.

File: cli/uninstall/uninstall.go (hunk 11 above)
Comment (themilchenko) [reply cli/uninstall/uninstall.go]: `errors.Is` is not working for this case. Fixed to second suggestion.

File: cli/uninstall/uninstall.go (hunk 12 above)
Comment (themilchenko) [reply cli/uninstall/uninstall.go]: Added regular expression version check symmetrically for `tt install` and `tt uninstall`.

File: cli/install/install.go [hunk 13]
```diff
@@ -495,7 +499,12 @@ func installTt(binDir string, installCtx InstallCtx, distfiles string) error {
 				return err
 			}
 			for _, ver := range versions {
-				if ttVersion == ver.Str || (ttVersion[:1] != "v" && "v"+ttVersion == ver.Str) {
+				versionMatches, err := regexp.Match(majorMinorPatchRegexp, []byte(ttVersion))
+				if err != nil {
+					return err
+				}
+				if ttVersion == ver.Str || (versionMatches && ttVersion[:1] != "v" &&
```
Comment (oleg-jukovec) [inline cli/install/install.go:506]: The regular expression `^[0-9]+\.[0-9]+\.[0-9]+`
) excludes the case because it only matches `begin_of_a_string+digits.digits.digits`:
```suggestion
				if ttVersion == ver.Str || (versionMatches &&
```

File: cli/uninstall/uninstall.go [hunk 14]
```diff
@@ -133,6 +155,25 @@ func UninstallProgram(program string, programVersion string, binDst string, head
...
+func getAllTtVersionFormats(ttVersion string) ([]string, error) {
+	var versionsToDelete []string
+
+	// Need to determine if we have x.y.z format in tt uninstall argument
+	// to make sure we add version prefix.
+	versionMatches, err := regexp.Match(majorMinorPatchRegexp, []byte(ttVersion))
+	if err != nil {
+		return versionsToDelete, err
+	}
+	if versionMatches && !strings.HasPrefix(ttVersion, "v") {
```
Comment (oleg-jukovec) [inline cli/uninstall/uninstall.go:169]: The same:
```suggestion
	if versionMatches {
```

File: cli/uninstall/uninstall_test.go [hunk 15]
```diff
@@ -143,3 +143,35 @@ func TestSearchLatestVersion(t *testing.T) {
...
+		ttVersion        string
+		expectedVersions []string
+		expectedError    error
+	}
+
+	cases := []testCase{
+		{
+			name:             "without prefix",
+			ttVersion:        "1.2.3",
+			expectedVersions: []string{"v1.2.3", "1.2.3"},
```
Comment (oleg-jukovec) [inline cli/uninstall/uninstall_test.go:159]: There should be reverse priority here because we want to prefer to delete a specified version:
```suggestion
			expectedVersions: []string{"1.2.3", "v1.2.3"},
```

File: cli/uninstall/uninstall.go (hunk 11 above)
Comment (oleg-jukovec) [reply cli/uninstall/uninstall.go]: > `errors.Is` is not working for this case

It seems like a problem becase `remove(` does not return the error variable as is. So it could be changed independently. It is better to return ErrNoTtInstalled from the `remove(` call (or from a nested call).

Comment (oleg-jukovec) [reply cli/uninstall/uninstall.go]: It seems like a problem because the `remove(` call does not return the error variable as is. This is not obvious and makes the code difficult to maintain. It is better to return `ErrNoTtInstalled` from the `remove(` call (or from a nested call).

Comment (themilchenko) [reply cli/uninstall/uninstall.go]: Now `remove(` is returning defined `errNoTtInstalled` when program name is "tt". It is now possible to use `errors.Is`.

File: cli/install/install.go (hunk 13 above)
Comment (themilchenko) [reply cli/install/install.go]: Deleted redundant expression.

File: cli/uninstall/uninstall_test.go (hunk 15 above)
Comment (themilchenko) [reply cli/uninstall/uninstall_test.go]: Changed to this behaviour.

**Review by oleg-jukovec — APPROVED** [review]
Thank you for the fix!

File: cli/install/install.go [hunk 16]
```diff
@@ -495,7 +499,11 @@ func installTt(binDir string, installCtx InstallCtx, distfiles string) error {
 				return err
 			}
 			for _, ver := range versions {
-				if ttVersion == ver.Str || (ttVersion[:1] != "v" && "v"+ttVersion == ver.Str) {
+				versionMatches, err := regexp.Match(majorMinorPatchRegexp, []byte(ttVersion))
+				if err != nil {
+					return err
+				}
+				if ttVersion == ver.Str || (versionMatches && "v"+ttVersion == ver.Str) {
```
[the remark this answers is not in the document]
Comment (themilchenko) [reply cli/install/install.go:506]: Then we won't have comparison in this expresion for case when the version will be without 'v' prefix.

File: cli/uninstall/uninstall.go [hunk 17]
```diff
@@ -23,7 +23,12 @@ const (
 		search.ProgramTt + "|" +
 		search.ProgramCe + "|" +
 		search.ProgramEe + ")"
-	verRegexp = "(?P<ver>.*)"
+	verRegexp             = "(?P<ver>.*)"
+	majorMinorPatchRegexp = `^[0-9]+\.[0-9]+\.[0-9]+`
```
[the remark this answers is not in the document]
Comment (themilchenko) [reply cli/uninstall/uninstall.go]: Deleted duplicate.

File: cli/install/install.go [hunk 18]
```diff
@@ -495,7 +499,11 @@ func installTt(binDir string, installCtx InstallCtx, distfiles string) error {
 				return err
 			}
 			for _, ver := range versions {
-				if ttVersion == ver.Str || (ttVersion[:1] != "v" && "v"+ttVersion == ver.Str) {
+				versionMatches, err := regexp.Match(majorMinorPatchRegexp, []byte(ttVersion))
```
[the remark this answers is not in the document]
Comment (themilchenko) [reply cli/install/install.go]: Took it out of the cycle.

**Review by psergee — APPROVED** [review]
lgtm
just minor comments left.

File: cli/install/install.go [hunk 19]
```diff
@@ -68,11 +68,15 @@ var unwindPatch []byte
...
-// read,write for user and only read for others.
-const defaultDirPermissions = 0755
+const (
+	// defaultDirPermissions is rights used to create folders.
+	// 0755 - drwxr-xr-x
+	// We need to give permission for all to execute
+	// read,write for user and only read for others.
+	defaultDirPermissions = 0755
+
+	MajorMinorPatchRegexp = `^[0-9]+\.[0-9]+\.[0-9]+`
```
[the remark this answers is not in the document]
Comment (oleg-jukovec) [reply cli/install/install.go:78]: `-alpha`, `-beta`, a commit hash and what we would like there in the future.

File: cli/uninstall/uninstall.go [hunk 20]
```diff
@@ -113,11 +120,28 @@ func UninstallProgram(program string, programVersion string, binDst string, head
 		}
 	}
 
+	versionsToDelete := []string{programVersion}
+	if program == search.ProgramTt {
```
[the remark this answers is not in the document]
Comment (themilchenko) [reply cli/uninstall/uninstall.go:124]: I thought that it is simpler to read: we go to the `getAllTtVersionFormats` block only if current program is `tt`.

File: cli/uninstall/uninstall.go [hunk 21]
```diff
@@ -53,6 +57,9 @@ func remove(program string, programVersion string, directory string,
 	path := filepath.Join(directory, fileName)
 
 	if _, err := os.Stat(path); os.IsNotExist(err) {
+		if program == search.ProgramTt {
+			return false, errTtNotInstalled
```
[the remark this answers is not in the document]
Comment (themilchenko) [reply cli/uninstall/uninstall.go:65]: Added separate error for each program.

File: cli/uninstall/uninstall.go (hunk 20 above)
[the remark this answers is not in the document]
Comment (themilchenko) [reply cli/uninstall/uninstall.go]: Added this logic into function.

File: cli/uninstall/uninstall_test.go [hunk 22]
```diff
@@ -143,3 +143,35 @@ func TestSearchLatestVersion(t *testing.T) {
...
+
+func TestGetAllVersionFormats(t *testing.T) {
+	type testCase struct {
+		name             string
+		ttVersion        string
+		expectedVersions []string
+		expectedError    error
+	}
+
+	cases := []testCase{
```
[the remark this answers is not in the document]
Comment (themilchenko) [reply cli/uninstall/uninstall_test.go:157]: Added.

File: test/integration/uninstall/test_uninstall.py [hunk 23]
```diff
@@ -306,3 +306,52 @@ def test_uninstall_tarantool_no_switch(tt_cmd, tmp_path):
         os.path.join(testdata_path, "bin", "tarantool_2.10.4"),
         os.path.join(testdata_path, "inc", "include", "tarantool_2.10.4")
     )
+
+
+@pytest.mark.parametrize("installed_versions, version_to_uninstall", [
+    (["v1.2.3"], "1.2.3"),
+    (["v1.2.3", "1.2.3"], "1.2.3")
```
[the remark this answers is not in the document]
Comment (themilchenko) [reply test/integration/uninstall/test_uninstall.py]: Added.

File: cli/install/install.go (hunk 19 above)
[the remark this answers is not in the document]
Comment (psergee) [reply cli/install/install.go:78]: > `-alpha`, `-beta`, a commit hash and what we would like there in the future.

If so, why don't we just rely of version.Parse. If it is passed, user provided version is a version, not a commit or PR num,

File: cli/uninstall/uninstall.go (hunk 21 above)
[the remark this answers is not in the document]
Comment (psergee) [reply cli/uninstall/uninstall.go:65]: omg, please no... Just use one error for all programs.

File: cli/install/install.go (hunk 19 above)
[the remark this answers is not in the document]
Comment (oleg-jukovec) [reply cli/install/install.go:78]: I don't see any problem using the function if we have it in the `cli/version`. To be honest, I didn’t know about it.
